### ISSUE TITLE
KSQL should support multi-line statements, without requiring explicit line continuation character

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1424]
KSQL should support multi-line statements, without requiring explicit line continuation character (`\`). 
Pretty much all other SQL interpreters work just fine without requiring an explicit line continuation character
It makes for ugly examples, and it's an unnecessary pain for users to remember.

**Comment by miguno** [comment]
@rmoff and @big-andy-coates : I remember we had a related issue were transitioning from interactive KSQL to headless KSQL (think: dev to prod) was problematic because you couldn't easily copy-paste your queries from interactive usage into a .sql file for headless usage.

Would Andy's PR at https://github.com/confluentinc/ksql/pull/2089 also help with that related issue? (I would have to dig to find the original ticket.)
