### ISSUE TITLE
KSQL throws NPE if no preceeding space before line continuation character

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1425]
```
ksql> SELECT MESSAGE\
> FROM RATINGS;io.confluent.ksql.parser.exception.ParseFailedException
Caused by: java.lang.NullPointerException
ksql> SELECT MESSAGE \
> FROM RATINGS;
is this as good as it gets? really ?
your team here rocks!
```

Related: #1424

**Comment by uurl** [comment]
@rmoff Fixed 👍

**Comment by big-andy-coates** [comment]
What is the required behaviour here?  I would say that the above statement is wrong, i.e. there should be a space before the slash or at the start of the next line. So IMHO, the issue here is that we get a NPE rather than a more helpful error message. 

Basically, the code should interpet

```
ksql> SELECT MESSAGE\
> FROM RATINGS;
```

As 

```
SELECT MESSAGEFROM RATINGS;
```

And should result in a helpful error message, such as something like:

```
ParseFailedException: expecting [, FROM] at pos 17.
```

**Comment by rmoff** [comment]
> the issue here is that we get a NPE rather than a more helpful error message.

I agree. Required behaviour is not just throwing a yucky NPE, but a nicely-formed error message.
