### ISSUE TITLE
UDFs should be able to accept NULL literal as argument.

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#1462]
The new UDF framework infers the method to execute using the method signature. However, if user passes `NULL` literal since we don't know the type for it we won't be able to find the matching function to execute. 
One way of dealing with such situation is assume that `NULL` type is `ANY` and find the matching function.
If there are more than one matching function have a protocol to pick one.

@dguy what do you think?

**Comment by apurvam** [comment]
cc @blueedgenick 

The context here is that there is a desire to write a UDF like `MASK(col, "X", 'x', '_')` where the three arguments define how the column text is to be modified. For instance the above call could mean:

1. Replace all upper case with 'X'.
2. Replace all lower case letters with 'x'.
3. Replace all digits with '_'.

Then if we want to call mask so that it doesn't modify upper case characters, it is natural to do something like `MASK(col, NULL, "x", "_")`.

However, the above won't work today since `NULL` doesn't have a type and the call won't match an existing UDF. 

If some arguments are `NULL`, then it may make sense to find a function matching the types of the non null arguments and then casting the null arguments to the appropriate type and then executing the function call.

**Comment by dguy** [comment]
Yes, that makes sense. Shouldn't be too hard to fix
