### ISSUE TITLE
Lost ability to set 'auto.offset.reset'='earliest' in script (RUN SCRIPT)

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1624]
This worked in earlier releases of KSQL but seems to have been removed in 5.0.0: the ability to specify

```bash
set 'auto.offset.reset'='earliest';
```

in a script called `test.ksql` that is run as:

```bash
ksql> run script 'test.ksql';
```

I'm filing this GH issue to make sure we don't lose track

**Comment by miguno** [comment]
@rodesai : Is this still a problem?

**Comment by miguno** [comment]
@ybyzek : I suppose setting offsets works in scripts for headless KSQL, it's only that it doesn't work when used in combination with RUN SCRIPT?

**Comment by ybyzek** [comment]
@miguno : it would require the team to validate latest behavior, it may have changed in recent releases.

**Comment by miguno** [comment]
@rodesai : Since you are assigned to this ticket, could you please verify?

**Comment by spena** [comment]
This is working in 5.4.

The output when executing the script does not show the SET was issued, but I did a test with a CSAS statement.

1. I added a CSAS statement in the .sql file without setting the offset config.
2. I run the RUN SCRIPT, and the CSAS stream was created.
3. Then I connected to KSQL, set the offset to earliest.
4. I run a transient query from the CSAS stream.
5. No data was returned because the CSAS stream is reading data from the last offset.

I then run the same above steps but setting the offset to the earliest in the .sql file. The result is that step #5 now returns the rows from the beginning of the source stream.
