### ISSUE TITLE
Could not find or load main class io.confluent.ksql.rest.server.KsqlServerMain

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#1793]
I try start Ksql 
```
[root@209test ksql]# ./bin/ksql-server-start  ./config/ksql-server.properties
Error: Could not find or load main class io.confluent.ksql.rest.server.KsqlServerMain
[root@209test ksql]#
```

**Comment by cricket007** [comment]
What release are you using? It should be found in the 5.0 release. Have you overwritten the `KSQL_CLASSPATH` environment variable with something else? 

https://github.com/confluentinc/ksql/blob/v5.0.0/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java

Can you add `set -xv` towards the top of the `ksql-server-start` and `ksql-run-class` scripts and add the output here?

**Comment by parth22594** [comment]
$ ./bin/ksql-server-start  ./config/ksql-server.properties
if [ $# -lt 1 ];
then
    echo "USAGE: $0 [-daemon] ksql-server.properties"
    exit 1
fi
+ '[' 1 -lt 1 ']'

base_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
 cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd
 dirname "${BASH_SOURCE[0]}"
+++ dirname ./bin/ksql-server-start
++ cd ./bin/..
++ pwd
+ base_dir=/e/KSQL/ksql-master
: "${KSQL_CONFIG_DIR:="$base_dir/config"}"
+ : /e/KSQL/ksql-master/config

: "${KSQL_LOG4J_OPTS:=""}"
+ : ''
if [ -z "$KSQL_LOG4J_OPTS" ] && [ -e "$KSQL_CONFIG_DIR/log4j-silent.properties"                                                                                                                 ]; then
  export KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:$KSQL_CONFIG_DIR/log4j-roll                                                                                                                ing.properties"
fi
+ '[' -z '' ']'
+ '[' -e /e/KSQL/ksql-master/config/log4j-silent.properties ']'
+ export KSQL_LOG4J_OPTS=-Dlog4j.configuration=file:/e/KSQL/ksql-master/config/l                                                                                                                og4j-rolling.properties
+ KSQL_LOG4J_OPTS=-Dlog4j.configuration=file:/e/KSQL/ksql-master/config/log4j-ro                                                                                                                lling.properties

EXTRA_ARGS="-name ksql-server -loggc"
+ EXTRA_ARGS='-name ksql-server -loggc'

if [ -z "$KSQL_OPTS" ]; then
  KSQL_OPTS=-Dksql.server.install.dir=$base_dir
else
  KSQL_OPTS="${KSQL_OPTS} -Dksql.server.install.dir=$base_dir"
fi
+ '[' -z '' ']'
+ KSQL_OPTS=-Dksql.server.install.dir=/e/KSQL/ksql-master

export KSQL_OPTS
+ export KSQL_OPTS

# TODO: Enable specification of properties via command-line arg in the KsqlRestA                                                                                                                pplication class
# so that useful defaults for bootstrap server, port, etc. can be established he                                                                                                                re

exec "$base_dir"/bin/ksql-run-class io.confluent.ksql.rest.server.KsqlServerMain                                                                                                                 $EXTRA_ARGS "$@"
+ exec /e/KSQL/ksql-master/bin/ksql-run-class io.confluent.ksql.rest.server.Ksql                                                                                                                ServerMain -name ksql-server -loggc ./config/ksql-server.properties
base_dir=$( cd -P "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
 cd -P "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd
 dirname "${BASH_SOURCE[0]}"
+++ dirname /e/KSQL/ksql-master/bin/ksql-run-class
++ cd -P /e/KSQL/ksql-master/bin/..
++ pwd
+ base_dir=/e/KSQL/ksql-master

# Log directory to use
if [ "x$LOG_DIR" = "x" ]; then
  LOG_DIR="$base_dir/logs"
fi
+ '[' x = x ']'
+ LOG_DIR=/e/KSQL/ksql-master/logs

# create logs directory
if [ ! -d "$LOG_DIR" ]; then
  mkdir -p "$LOG_DIR"
fi
+ '[' '!' -d /e/KSQL/ksql-master/logs ']'

: "${KSQL_CLASSPATH:=""}"
+ : ''
: "${KSQL_LOG4J_OPTS:=""}"
+ : -Dlog4j.configuration=file:/e/KSQL/ksql-master/config/log4j-rolling.properti                                                                                                                es
: "${KSQL_JMX_OPTS:=""}"
+ : ''
: "${KSQL_OPTS:=""}"
+ : -Dksql.server.install.dir=/e/KSQL/ksql-master
: "${KSQL_HEAP_OPTS:=""}"
+ : ''
: "${KSQL_JVM_PERFORMANCE_OPTS:=""}"
+ : ''
: "${JMX_PORT:=""}"
+ : ''
: "${JAVA_HOME:=""}"
+ : 'C:\Program Files\Java\jdk1.8.0_91'

# Development jars. `mvn package` should collect all the required dependency jar                                                                                                                s here
for project in ksql-engine ksql-examples ksql-rest-app ksql-cli; do
    for dir in "$base_dir/$project/target/$project"-*-development; do
      KSQL_DIR="$dir/share/java/$project"
      if [ -d "$KSQL_DIR" ]; then
        KSQL_CLASSPATH="$KSQL_CLASSPATH:$KSQL_DIR/*"
      fi
    done
done
+ for project in ksql-engine ksql-examples ksql-rest-app ksql-cli
+ for dir in '"$base_dir/$project/target/$project"-*-development'
+ KSQL_DIR='/e/KSQL/ksql-master/ksql-engine/target/ksql-engine-*-development/sha                                                                                                                re/java/ksql-engine'
+ '[' -d '/e/KSQL/ksql-master/ksql-engine/target/ksql-engine-*-development/share                                                                                                                /java/ksql-engine' ']'
+ for project in ksql-engine ksql-examples ksql-rest-app ksql-cli
+ for dir in '"$base_dir/$project/target/$project"-*-development'
+ KSQL_DIR='/e/KSQL/ksql-master/ksql-examples/target/ksql-examples-*-development                                                                                                                /share/java/ksql-examples'
+ '[' -d '/e/KSQL/ksql-master/ksql-examples/target/ksql-examples-*-development/s                                                                                                                hare/java/ksql-examples' ']'
+ for project in ksql-engine ksql-examples ksql-rest-app ksql-cli
+ for dir in '"$base_dir/$project/target/$project"-*-development'
+ KSQL_DIR='/e/KSQL/ksql-master/ksql-rest-app/target/ksql-rest-app-*-development                                                                                                                /share/java/ksql-rest-app'
+ '[' -d '/e/KSQL/ksql-master/ksql-rest-app/target/ksql-rest-app-*-development/s                                                                                                                hare/java/ksql-rest-app' ']'
+ for project in ksql-engine ksql-examples ksql-rest-app ksql-cli
+ for dir in '"$base_dir/$project/target/$project"-*-development'
+ KSQL_DIR='/e/KSQL/ksql-master/ksql-cli/target/ksql-cli-*-development/share/jav                                                                                                                a/ksql-cli'
+ '[' -d '/e/KSQL/ksql-master/ksql-cli/target/ksql-cli-*-development/share/java/                                                                                                                ksql-cli' ']'

# Production jars - each one is prepended so they will appear in reverse order.                                                                                                                  KSQL jars take precedence over other stuff passed in via CLASSPATH env var
for library in "confluent-common" "ksql-examples" "rest-utils" "ksql-engine" "ks                                                                                                                ql-rest-app" "ksql-cli" "ksql" "monitoring-interceptors"; do
  DIR="$base_dir/share/java/$library"
  if [ -d "$DIR" ]; then
    KSQL_CLASSPATH="$DIR/*:$KSQL_CLASSPATH"
  fi
done
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/confluent-common
+ '[' -d /e/KSQL/ksql-master/share/java/confluent-common ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/ksql-examples
+ '[' -d /e/KSQL/ksql-master/share/java/ksql-examples ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/rest-utils
+ '[' -d /e/KSQL/ksql-master/share/java/rest-utils ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/ksql-engine
+ '[' -d /e/KSQL/ksql-master/share/java/ksql-engine ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/ksql-rest-app
+ '[' -d /e/KSQL/ksql-master/share/java/ksql-rest-app ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/ksql-cli
+ '[' -d /e/KSQL/ksql-master/share/java/ksql-cli ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/ksql
+ '[' -d /e/KSQL/ksql-master/share/java/ksql ']'
+ for library in '"confluent-common"' '"ksql-examples"' '"rest-utils"' '"ksql-en                                                                                                                gine"' '"ksql-rest-app"' '"ksql-cli"' '"ksql"' '"monitoring-interceptors"'
+ DIR=/e/KSQL/ksql-master/share/java/monitoring-interceptors
+ '[' -d /e/KSQL/ksql-master/share/java/monitoring-interceptors ']'

# logj4 settings
if [ -z "$KSQL_LOG4J_OPTS" ]; then
  # Test for files from dev -> packages so this will work as expected in dev if                                                                                                                 you have packages
  # installed
  if [ -e "$base_dir/config/log4j.properties" ]; then # Dev environment
    KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:$base_dir/config/log4j.propertie                                                                                                                s"
  elif [ -e "$base_dir/etc/ksql/log4j.properties" ]; then # Simple zip file layo                                                                                                                ut
    KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:$base_dir/etc/ksql/log4j.propert                                                                                                                ies"
  elif [ -e "/etc/ksql/log4j.properties" ]; then # Normal install layout
    KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/ksql/log4j.properties"
  fi
fi
+ '[' -z -Dlog4j.configuration=file:/e/KSQL/ksql-master/config/log4j-rolling.pro                                                                                                                perties ']'

 KSQL_LOG4J_OPTS="-Dksql.log.dir=$LOG_DIR ${KSQL_LOG4J_OPTS}"
+ KSQL_LOG4J_OPTS='-Dksql.log.dir=/e/KSQL/ksql-master/logs -Dlog4j.configuration                                                                                                                =file:/e/KSQL/ksql-master/config/log4j-rolling.properties'

# JMX settings
if [ -z "$KSQL_JMX_OPTS" ]; then
  KSQL_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.a                                                                                                                uthenticate=false -Dcom.sun.management.jmxremote.ssl=false "
fi
+ '[' -z '' ']'
+ KSQL_JMX_OPTS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.a                                                                                                                uthenticate=false -Dcom.sun.management.jmxremote.ssl=false '

# JMX port to use
if [ ! -z "$JMX_PORT" ]; then
  KSQL_JMX_OPTS="$KSQL_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT "
fi
+ '[' '!' -z '' ']'

# Generic jvm settings you want to add
if [ -z "$KSQL_OPTS" ]; then
  KSQL_OPTS=""
fi
+ '[' -z -Dksql.server.install.dir=/e/KSQL/ksql-master ']'

# Which java to use
if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi
+ '[' -z 'C:\Program Files\Java\jdk1.8.0_91' ']'
+ JAVA='C:\Program Files\Java\jdk1.8.0_91/bin/java'

# Memory options
if [ -z "$KSQL_HEAP_OPTS" ]; then
  KSQL_HEAP_OPTS="-Xmx3g"
fi
+ '[' -z '' ']'
+ KSQL_HEAP_OPTS=-Xmx3g

# JVM performance options
if [ -z "$KSQL_JVM_PERFORMANCE_OPTS" ]; then
  KSQL_JVM_PERFORMANCE_OPTS="-server -XX:+UseConcMarkSweepGC -XX:+CMSClassUnload                                                                                                                ingEnabled -XX:+CMSScavengeBeforeRemark -XX:+ExplicitGCInvokesConcurrent -XX:New                                                                                                                Ratio=1 -Djava.awt.headless=true"
fi
+ '[' -z '' ']'
+ KSQL_JVM_PERFORMANCE_OPTS='-server -XX:+UseConcMarkSweepGC -XX:+CMSClassUnload                                                                                                                ingEnabled -XX:+CMSScavengeBeforeRemark -XX:+ExplicitGCInvokesConcurrent -XX:New                                                                                                                Ratio=1 -Djava.awt.headless=true'

if [ $# -lt 1 ];
then
  echo "USAGE: $0 [-daemon] [opts] [-help]"
    exit 1
fi
+ '[' 5 -lt 1 ']'

MAIN="$1"
+ MAIN=io.confluent.ksql.rest.server.KsqlServerMain
shift
+ shift

DAEMON_NAME=""
+ DAEMON_NAME=
GC_LOG_ENABLED=""
+ GC_LOG_ENABLED=
DAEMON_MODE=""
+ DAEMON_MODE=
HELP=""
+ HELP=
if [ "$1" = "help" ]; then
  HELP="true"
fi
+ '[' -name = help ']'
while [ $# -gt 0 ]; do
  COMMAND="$1"
  case "$COMMAND" in
    -name)
      DAEMON_NAME=$2
      shift 2
      ;;
    -loggc)
      GC_LOG_ENABLED="true"
      shift
      ;;
    -daemon)
      DAEMON_MODE="true"
      shift
      ;;
    -help)
      HELP="true"
      shift
      ;;
   *)
      break
      ;;
  esac
done
+ '[' 4 -gt 0 ']'
+ COMMAND=-name
+ case "$COMMAND" in
+ DAEMON_NAME=ksql-server
+ shift 2
+ '[' 2 -gt 0 ']'
+ COMMAND=-loggc
+ case "$COMMAND" in
+ GC_LOG_ENABLED=true
+ shift
+ '[' 1 -gt 0 ']'
+ COMMAND=./config/ksql-server.properties
+ case "$COMMAND" in
+ break


# GC options
GC_FILE_SUFFIX='-gc.log'
+ GC_FILE_SUFFIX=-gc.log
GC_LOG_FILE_NAME=''
+ GC_LOG_FILE_NAME=
KSQL_GC_LOG_OPTS=""
+ KSQL_GC_LOG_OPTS=
if [ "x$GC_LOG_ENABLED" = "xtrue" ]; then
  GC_LOG_FILE_NAME=$DAEMON_NAME$GC_FILE_SUFFIX
  # The first segment of the version number, which is '1' for releases before Ja                                                                                                                va 9
  # it then becomes '9', '10', ...
  # Some examples of the first line of `java --version`:
  # 8 -> java version "1.8.0_152"
  # 9.0.4 -> java version "9.0.4"
  # 10 -> java version "10" 2018-03-20
  # 10.0.1 -> java version "10.0.1" 2018-04-17
  # We need to match to the end of the line to prevent sed from printing the cha                                                                                                                racters that do not match
  JAVA_MAJOR_VERSION=$($JAVA -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*                                                                                                                $/\1/p')
  if [[ "$JAVA_MAJOR_VERSION" -ge "9" ]] ; then
    KSQL_GC_LOG_OPTS="-Xlog:gc*:file=$LOG_DIR/$GC_LOG_FILE_NAME:time,tags:fileco                                                                                                                unt=10,filesize=102400"
  else
    KSQL_GC_LOG_OPTS="-Xloggc:$LOG_DIR/$GC_LOG_FILE_NAME -verbose:gc -XX:+PrintG                                                                                                                CDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation                                                                                                                 -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"
  fi
fi
+ '[' xtrue = xtrue ']'
+ GC_LOG_FILE_NAME=ksql-server-gc.log
$JAVA -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p'
++ 'C:\Program' 'Files\Java\jdk1.8.0_91/bin/java' -version
++ sed -E -n 's/.* version "([0-9]*).*$/\1/p'
+ JAVA_MAJOR_VERSION=
+ [[ '' -ge 9 ]]
+ KSQL_GC_LOG_OPTS='-Xloggc:/e/KSQL/ksql-master/logs/ksql-server-gc.log -verbose                                                                                                                :gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGC                                                                                                                LogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M'


if [ "x$HELP" = "xtrue" ]; then
  exec "$JAVA" -cp "$KSQL_CLASSPATH" "$MAIN" --help
  exit 1
fi
+ '[' x = xtrue ']'

OPTIONS=($KSQL_HEAP_OPTS)
+ OPTIONS=($KSQL_HEAP_OPTS)
OPTIONS+=($KSQL_JVM_PERFORMANCE_OPTS)
+ OPTIONS+=($KSQL_JVM_PERFORMANCE_OPTS)
OPTIONS+=($KSQL_JMX_OPTS)
+ OPTIONS+=($KSQL_JMX_OPTS)
OPTIONS+=($KSQL_LOG4J_OPTS)
+ OPTIONS+=($KSQL_LOG4J_OPTS)
OPTIONS+=($KSQL_OPTS)
+ OPTIONS+=($KSQL_OPTS)
OPTIONS+=($KSQL_GC_LOG_OPTS)
+ OPTIONS+=($KSQL_GC_LOG_OPTS)

# Launch mode
if [ "x$DAEMON_MODE" = "xtrue" ]; then
  DAEMON_STDOUT_FILE="$LOG_DIR/ksql.out"
  echo "Writing console output to $DAEMON_STDOUT_FILE"
  nohup "$JAVA" -cp "$KSQL_CLASSPATH" "${OPTIONS[@]}" "$MAIN" "$@" 2>&1 < /dev/n                                                                                                                ull > "$DAEMON_STDOUT_FILE" &
else
  exec "$JAVA" -cp "$KSQL_CLASSPATH" "${OPTIONS[@]}" "$MAIN" "$@"
fi
+ '[' x = xtrue ']'
+ exec 'C:\Program Files\Java\jdk1.8.0_91/bin/java' -cp '' -Xmx3g -server -XX:+U                                                                                                                seConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark -XX                                                                                                                :+ExplicitGCInvokesConcurrent -XX:NewRatio=1 -Djava.awt.headless=true -Dcom.sun.                                                                                                                management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun                                                                                                                .management.jmxremote.ssl=false -Dksql.log.dir=/e/KSQL/ksql-master/logs -Dlog4j.                                                                                                                configuration=file:/e/KSQL/ksql-master/config/log4j-rolling.properties -Dksql.se                                                                                                                rver.install.dir=/e/KSQL/ksql-master -Xloggc:/e/KSQL/ksql-master/logs/ksql-serve                                                                                                                r-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTime                                                                                                                Stamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100                                                                                                                M io.confluent.ksql.rest.server.KsqlServerMain ./config/ksql-server.properties
Error: Could not find or load main class io.confluent.ksql.rest.server.KsqlServe                                                                                                                rMain




after set -xv in the top in ksql-server-start and ksql-run-class

**Comment by eksantrik** [comment]
Hello, I am having the same issue. I dowloaded the latest version from github and getting the following error when I try to start the server:

[root@Ksql bin]# ./ksql-server-start ~/downloads/ksql/config/ksql-server.properties
Error: Could not find or load main class io.confluent.ksql.rest.server.KsqlServerMain

Do you have any clues how to fix this?

Thanks

**Comment by cricket007** [comment]
I don't think these scripts are tested on Windows / Cygwin / WSL. 

The problem starts at the beginning 

```
base_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd
dirname "${BASH_SOURCE[0]}"
+++ dirname ./bin/ksql-server-start
++ cd ./bin/..
++ pwd

    base_dir=/e/KSQL/ksql-master
```

That `/e/KSQL/ksql-master` is likely not a real folder on your system. 

That causes the classpath to become unresolvable, at the end `exec 'C:\Program Files\Java\jdk1.8.0_91/bin/java' -cp ''`, and thus "class not found"

**Comment by cricket007** [comment]
Comment on #402 if you would like the issue reopened

**Comment by dmarupov** [comment]
I am having the same error. I have downloaded the binary version and unzipped it and then when I try to run ksql-server-start or ksql I get the same error. I do not have this issue when I run ksqldb with Confluent Platform. I would really like to be able to run ksqldb without the docker or Confluent Platform. Please let me know how I could troubleshoot this further?

Thank you.
