### ISSUE TITLE
Extend command messages to include cookie referencing request and use this to map to completion futures

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1860]
In PR #1856 we  fail registration if a future is already registered, to prevent a caller from receiving a future for a different statement. However this problem can still happen across servers - a request from a different server can slide into the command topic before this one, and the executor thread will wind up completing this future on the basis of processing that statement, which is clearly wrong. To solve that we need to put something in the command message to reference back to the future the server thread is waiting on.

**Comment by vcrfxia** [comment]
@rodesai will this still be a concern after @stevenpyzhang 's work on https://github.com/confluentinc/ksql/issues/2435?

**Comment by stevenpyzhang** [comment]
This shouldn't be an issue anymore since `a request from a different server can slide into the command topic before this one` can't happen now because the request would fail to be enqueued now since another server has initialized and completed a transaction so the current request would fail to enqueue.
