### ISSUE TITLE
How to add more tables with TOPIC?

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#1916]
eg:

SQL-1:
```create table t1 with(kafka_topic='topic_1',value_format='json') as select columns from stream;```

SQL-2:
```create table t2 with(kafka_topic='topic_1',value_format='json') as select columns from stream;```

Error:
Cannot add the new topic.Another topic with the same name alread exists;

How to fix this problem.
Thanks.

**Comment by big-andy-coates** [comment]
Hi @sangli00,

Using the same output topic for two tables is is not currently supported by KSQL and is, I think, unlikely ever to be. 

The reason for this is that KSQL would not be able to keep the two tables consistent. The topic behind a table is only used for recovery. While the KSQL statement is running the topic is only written too, not read from. While running, KSQL keeps the tables state in memory/rocksdb. So if there were two table queries running, backed by the same topic, they would not see each others changes. 

I hope I've explained that OK.

However, might work for you is to join the two streams and then build a table from this. e.g. 

```
create stream joined with(...) as 
   select columns from 
   stream_1 s1 full join stream_2 s2 on s1.rowkey = s2.rowkey;

create table t with(...) as
   select columns from joined;
```

This works because the table is built from a single query, with the right data being supplied by the join.

Hope this helps.

Any questions, please let me know. Otherwise, kindly close this issue as resolved.

Thanks,

Andy

**Comment by sangli00** [comment]
@big-andy-coates 
```create table seconds_check as select count(*) as total,user_ip,data_resource_url from stream
window hopping(size 10 seconds,advance by 10 seconds)
group by user_ip,data_resource_url
having count(*) > 10;```


```create table hours_check as select count(*) as total,user_ip,data_resource_url from stream
window hopping(size 1 hours,advance by 1 hours)
group by user_ip,data_resource_url
having count(*) > 100;```



create table joined as select * from seconds_check t1 full join hours_check t2 
on t1.rowkey = t2.rowkey;


I insert data to ```stream```, joined table is not find any data,but ```seconds_check```,```hours_check```is OK.

**Comment by sangli00** [comment]
If I don't create table, 
```select * from seconds_check t1 full join hours_check t2
on t1.rowkey = t2.rowkey;
``` is OK.

**Comment by big-andy-coates** [comment]
Hi @sangli00,

What you're trying to do here is join to windowed tables. For the join to work the key of the two tables need to match. The key includes the window, e.g. they will be in a format similar to `<user_ip>,<data_resource_url> : Window{<window_start>,<window_end>}`.  Because your two tables use different window sizes the two streams will never join, as the keys will never match.

It's probably a KSQL bug that this isn't reporting an error.  You'll probably see an error in the server log.

**Comment by sangli00** [comment]
@big-andy-coates

**Comment by sangli00** [comment]
@big-andy-coates  
If i have hundred tables in KSQL ,others system need this data, How to transform others system? 
Why more tables cannot add topic?  



image URL: https://www.processon.com/view/link/5ba9d1a3e4b075b9fe5565da
![b188f1b3-b0b9-497f-a763-4068ee40ee50](https://user-images.githubusercontent.com/3765918/45996212-f2416200-c0cd-11e8-9ba3-004030139cfc.png)

WEB system use REST API, make rule SQL in KSQL system. like:
```
curl -s -X POST http://127.0.0.1:8088/ksql -H 'Content-type:application/json' \
-d '{"ksql":"create table tab as select count(*),user_ip,cookie from generic_stream window hopping(size 10 second,advance by 10 seconds)  where xxx having count(*) > 10;"}'
```

diff rule is diff SQL.and used  KSQL transform data to TOPIC like:
```
create table transform_tab with(kafka_topic='output',value_format='json') as select * from tab;
```

Others system just only know ```output```topic,any time get KSQL data .
but now,KSQL cannot support more tables add one topic.  
So,I can't  do this，or how to transform data to topic? 

Thank you very much. (*￣︶￣)

**Comment by big-andy-coates** [comment]
Hi @sangli00 

> error: Column MAX cannot be resolved.

This means the source data does not have a column called MAX, yet you are trying to group-by such a column. 

> If i have hundred tables in KSQL ,others system need this data, How to transform others system? Why more tables cannot add topic?

I've explained [here](https://github.com/confluentinc/ksql/issues/1916#issuecomment-423084220) why its not possible for multiple tables in KSQL to share a common underlying topic.  It just wouldn't work.  Also, I've explained why your attempts to join two tables hasn't given the output you expect. 

If you want to munge all of your tables into a single stream of change events, then you can do so by having multiple tables, e.g.

```
create table t1 with (kafka_topic='t1') as select something from something group by something;

create table t2 with (kafka_topic='t2') as select something from something group by something;

... 
```

Then munge the changes together by re-importing the topic and using  'INTO' statements to share an output topic

```
-- import topics underlying tables back into KSQL as a stream of changes:
create stream s1 with (kafka_topic='t1') ..
create stream s2 with (kafka_topic='t2') ...

-- munge these together into a single output stream:
create stream output as select * from s1 ...;
insert into output select * from s2 ...;
```

I've not played around with this too much myself, but it may give you want you want.

**Comment by big-andy-coates** [comment]
No `case` support as yet. It's coming. There's a Github issue tracking that somewhere.

If you're problem is now resolved, am I ok to close this issue now?

**Comment by sangli00** [comment]
@big-andy-coates  Thanks.

**Comment by sangli00** [comment]
@big-andy-coates  I have problem about Agg statement.
eg:
stream statement
```
create stream(user_ip bigint,app_ip bigint,url) with(kafka_topic='topics',value_format='json');
```
table statement
```
create table tab1 as select count(*) as total,user_ip,url from stream 
window hopping(size 60 seconds,advance by 60 seconds)
group by user_ip,url 
having(count(*)) > 10;
```
but now,I need get app_ip, ```group by ```  cannot do this.
How to get app_id in this statement ?
thanks.
