### ISSUE TITLE
KSQL sampling window

### ISSUE THREAD

**Issue by larryxia-ddl** [confluentinc/ksql#1924]
I run the following query. 
select  requesttype, count(*) count, sum(amount) total, max(amount) max_amount from money_transfer WINDOW TUMBLING  (SIZE 10 minutes) group by requesttype;

The result is like this
Requesttype|count|sum|max
fundtransfer | 346 | 11369000 | 100000
fundtransfer | 349 | 11459000 | 100000
fundtransfer | 352 | 11587500 | 100000
fundtransfer | 355 | 11732500 | 100000
fundtransfer | 358 | 11782500 | 100000
fundtransfer | 359 | 11802500 | 100000
fundtransfer | 365 | 11929000 | 100000
fundtransfer | 368 | 11952000 | 100000
fundtransfer | 370 | 11995500 | 100000
fundtransfer | 372 | 12065500 | 100000

Why the count increment is random? It seem there is another sampling window that I can't control.  In my understanding, if I define the tumbling window, I should get either 1 or exactly number of count records. But from tests I did, it seems that KSQL have another sampling interval that we can't control, the return is more like mini batch. Can you confirm, can we change the sampling window.

**Comment by big-andy-coates** [comment]
Hi @larryxia-ddl,

Internal KSQL uses Kafka Streams, and the streams library performs a certain amount buffering so that new values are not output on every new event.  The buffering can be controlled via `ksql.streams.cache.max.bytes.buffering`. Setting this to zero will turn off buffering, so you'll see a new output record for each input record. While increasing the value will decrease the frequency at which events are output.  The `commit.interval.ms` setting can also be tuned to control the maximum time an output record can be buffered for.

We're aware these settings are a little opaque, and there is some work planned to improve control in this area.

If you're happy with this answer to your question please close this issue. If you have any following up questions please post them here.

Thanks,

Andy

**Comment by larryxia-ddl** [comment]
Thanks you for your explain. I am fine as long as it is configurable. and we know what is expected.
