### ISSUE TITLE
Data not showing up where I expect it

### ISSUE THREAD

**Issue by afterlifenirvana** [confluentinc/ksql#1973]
Hi,

- I created an empty topic by name `events`.
- Then created a stream over it named `events_stream`. 
- Then registered a query as such `insert into events_stream select * where someFilter`.
 
On doing `show topics` it is showing one more topic named `events_stream` with registered flag false.

when i tail the topic creatd by me. On sending the data the filtered data is available in the `events_stream` topic but not in `events`. Is supposed to be this way ??

**Comment by miguno** [comment]
Hi @afterlifenirvana.

Not sure I understand:  You are saying you do see data in `events_stream` (the stream you created) but not in the stream's underlying "source" topic called `events`?

**Comment by afterlifenirvana** [comment]
- - I made the topic explicitly with kafka-topics.sh named events;
-- created a stream over it events_stream with KAFKA_TOPIC='events';
-- did an insert into events_stream from x where some conditions;
-- I'm seeing the results in events_stream TOPIC from consumer which i did not create and not in events which i did create.

**Comment by miguno** [comment]
Could you share the exact commands?  Also, what is `x` in `from x`?

**Comment by vcrfxia** [comment]
Hey @afterlifenirvana are you still seeing this issue?

If I understand correctly, you're saying that the `INSERT INTO` query you ran created a new topic called `ALERTS_STREAM` which you did not expect to happen, and that the query output was written to the `ALERTS_STREAM` topic rather than the `alerts` topic as you expected. If my understanding is correct, that is indeed unexpected behavior and warrants investigation if the behavior is still present on the latest version of KSQL.

I'm closing this issue for now as it's been inactive for a while and a lot has changed in KSQL since, but please reopen it if you're still seeing the unexpected behavior. Thanks!
