### ISSUE TITLE
Cannot define a TABLE without KEY column

### ISSUE THREAD

**Issue by darionyaphet** [confluentinc/ksql#2062]
When I learn KSQL from Getting Started , try the `CREATE TABLE` command , I found exception `Cannot define a TABLE without providing the KEY column name in the WITH clause.`

`CREATE TABLE users_original (registertime bigint, gender varchar, regionid varchar, userid varchar) WITH (kafka_topic='users', value_format='JSON');`

**Comment by jschulenklopper** [comment]
@darionyaphet, do you have a link to the example / sample that you're following? All of the examples I saw require a key colum for the `CREATE TABLE` command (excluding the `CREATE STREAM AS SELECT` and `CREATE TABLE AS SELECT` cases).

See https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#create-table. `KEY` is a required property. You're getting the exception because you're not following the specification :-)

**Comment by big-andy-coates** [comment]
See #2745, which drops the requirement for having a KEY defined on a table and makes it just an optimisation.
