### ISSUE TITLE
About KSQL Server restart problem

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#2113]
I restart ksql:
```
[root@localhost confluent-5.0.0]# ./bin/confluent start
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /tmp/confluent.aSjQ7OOD
Starting zookeeper
zookeeper is [UP]
Starting kafka
kafka is [UP]
Starting schema-registry
schema-registry is [UP]
Starting kafka-rest
kafka-rest is [UP]
Starting connect
Kafka Connect failed to start
connect is [DOWN]
Starting ksql-server
ksql-server is [UP]
```

```Starting connect``` this is connect what?  I need add some store? 
how to build it?

why use ```/tmp``` folder? 
```Using CONFLUENT_CURRENT: /tmp/confluent.aSjQ7OOD``` All queries store in this folder?
I restart queries is lost in KSQL:
![36050e576665b22916e1a140f68d978d](https://user-images.githubusercontent.com/3765918/47902021-4c4af980-debc-11e8-8dbb-66b303325b43.png)

**Comment by apurvam** [comment]
You don't need connect to run ksql. It is just started as part of the package. It should "just work", does it keep failing?

Also, this CLI is meant only for demos, and not production use. That's why it uses the tmp folder. See this docs page for learning how to configure and start ksql for production: https://docs.confluent.io/current/ksql/docs/operations.html

**Comment by apurvam** [comment]
I'm going to close this. Please reopen if you have further questions.

**Comment by cricket007** [comment]
> Starting connect this is connect what? I need add some store?
> how to build it?

This seems to be a Kafka Connect issue, not a KSQL issue. 

Kafka Connect server is not required to use KSQL
