### ISSUE TITLE
KsqlEngine should not convert Exception to ParseFailedException

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#2203]
KsqlEngine converts all exceptions thrown by the parser into ParseFailed exception. ParseFailedException is assumed to be caused by an error in the received statement. The parser could fail for valid statements (e.g. due to a ksql bug).

**Comment by big-andy-coates** [comment]
Hey @rodesai, this may have been fixed with my recent changes in this area.

`KsqlEngine` now no longer throws `new ParseFailedException`. Instead, it throws the super of `ParseFailedException`: `KsqlStatementException`, e.g.

```java
} catch (final Exception e) {
      throw new KsqlStatementException("Exception while processing statement: " + e.getMessage(),
          statement.getStatementText(), e);
    }
```

Personally, I think this is fine.  While the failure may not be a result of the statement, it did occur during the processing of the statement. So I think its OK to throw a `KsqlStatementException`, with a generic 'processing error' type message, here.

What do you think?  Close this is you're happy, or else let me know your thoughts and I'll look into it.

**Comment by big-andy-coates** [comment]
Actually, think on this a little more, I'll check what message the user gets back from the rest api, as it may well not be much different. It shouldn't be a 'bad statement' or 'bad request' style error message if the error is more generic.

**Comment by rodesai** [comment]
Yep that was exactly my concern. We're using the exception type to determine what status code to send back. Currently KsqlException prompts a 400 response code. So we shouldn't convert arbitrary exceptions (which really are indicative of something going wrong on our end) into 400s.

**Comment by big-andy-coates** [comment]
Resolved by above. 

@rodesai, if you have the time / inclination would you double check?
