### ISSUE TITLE
ROWKEY does not change by using 'key' property

### ISSUE THREAD

**Issue by TobiasHauck** [confluentinc/ksql#2257]
Imagine I've got a topic ```foo``` containing avro data:
```
{ id: "634576745", someString: "test123", customerId: "111" },
...
```

where ```id``` has exactly the same value than the kafka message key. So the kafka messages look like:
```{ "634576745": { id: "634576745", someString: "test123", customerId: "111" } }```

Now I want to build a table and use the customerId as the key. So I'm following the documentation and use the "key" property:

```CREATE TABLE FOO WITH (kafka_topic='foo', value_format='avro', key='customerId');```

What I expect is the ROWKEY to become the customerId, but what I get is (After a ```SELECT * FROM FOO;```):
```[ 37443657647, "634576745", "634576745", "test123", "111" ]```, so the ROWKEY has not changed at all.

Am I doing something wrong or is this a bug?

**Comment by rmoff** [comment]
HI @TobiasHauck, this is currently expected behaviour. `WITH (KEY='foo')` is simply _advising_ KSQL that column `foo` in the payload matches the key of the Kafka message. 

If you want to change the key of a message _you_ need to repartition it, which KSQL does support with the `PARTITION BY` syntax. See this for details: https://www.confluent.io/stream-processing-cookbook/ksql-recipes/setting-kafka-message-key
