### ISSUE TITLE
`Lag` function to compare the current value to the last received 

### ISSUE THREAD

**Issue by datajoely** [confluentinc/ksql#2562]
If you have a stream of coordinates coming in, it's a little painful to compare the `GEO_DISTANCE()`  between them.

Some ability to get the last message may be useful.

**Comment by big-andy-coates** [comment]
Hi @datajoely,

Can you explain what you mean by last message?

I'm guessing its the message before the one being processed... however this is not easy to achieve in stream processing due to many things, but mainly two:

First, to be able to scale, stream processing, KSQL included, partitions the data. Each KSQL server running in a cluster only sees some of the partitions of data and each partition is processed separately.  So the concept of 'last message' would need to be 'last message in the same partition'.

Second, stream processing must deal with 'late data', i.e. messages that appear later in the stream of messages that have a event time that means they should have been seen much earlier in the stream.  This further complicates the concept of 'last message' as the message before the current one is not fixed: it can change as later messages are found that have an earlier event time than those already processed.

That said, it is possible to write a UDF that caches the previous message seen, (per partition), and exposes its fields to the next message if you wanted.  Such processing would be 'offset ordered' as opposed to 'event-time ordered', so would not necessarily have a predictable outcome, but it may solve your use-case.

Hope this helps.

**Comment by datajoely** [comment]
This makes a lot of sense, additionally after working with KSQL a little longer simply joining the stream to itself via a window is pretty effective!

**Comment by holgerbrandl** [comment]
Could you @datajoely give an example about how a such self-join could be implemented to provide a shift by N events  (or N=1event to get started with) ?  E.g. to differentiate a function as described in https://stackoverflow.com/questions/54713760/kafka-time-difference-last-two-records-ksql-or-other

In my understanding, a convenient LAG functionality is still missing in KSQL and this ticket not really solved yet.  A common task users may want to implement with Kafka/KSQL is change rate calculation which could be written with SQL (in most dialects) as 
```
SELECT sensor, difference = value - lag(value) FROM bla GROUP BY sensor
```
However, also after quite some reading of KSQL documentation & discussions, I could not find a simple way to do so.

@big-andy-coates Would the current UDF API really be applicable for this problem: Simple UDFs don't have a state according to the [docs](https://docs.confluent.io/current/ksql/docs/developer-guide/udf.html), and UADFs seem to be wrong because the problem is not about aggregation. The closest pointer to a solution I could find so far is to use the processor API with a local state store as outlined in <https://stackoverflow.com/questions/58745670/kafka-compare-consecutive-values-for-a-key

**Comment by holgerbrandl** [comment]
@datajoely I followed your suggestion and could create a somehow self-contained example illustrating your idea of using a self-join for differentiation. See https://stackoverflow.com/questions/54713760/kafka-time-difference-last-two-records-ksql-or-other/58970040#58970040

**Comment by datajoely** [comment]
Hi @holgerbrandl - thanks for getting back to me!

@jiriklein and myself initially experimented with doing this sort of approach, but it became complex when when we were doing it across several disparate topics that can only really join on time.   

The data source we were working with was designed to only send change events, but the domain we're working with needed to model some concept of 'active state' if that makes sense.

Since our data sizes were pretty small, we ended up preprocessing the information in python before producing the messages. This was done with simplicity in mind, but kind of defeats the object of stream processing.

The actual function I would like in this situation is something like [this](https://spark.apache.org/docs/2.1.0/api/python/pyspark.sql.html#pyspark.sql.DataFrameNaFunctions.fill) in the Spark world. This is to say, a simple method of carrying forward the last received value received for a particular field.

**Comment by etkaminski** [comment]
Hello @holgerbrandl 
Is it actually possible to solve this issue on KSQL? 
https://stackoverflow.com/questions/58745670/kafka-compare-consecutive-values-for-a-key 

I am trying to do something similar and I am not finding the way. 
It would be a huge help.
Thanks

**Comment by holgerbrandl** [comment]
@etkaminski Have you checked out the other stackoverflow reference mentioned earlier?

**Comment by etkaminski** [comment]
Hi Holger thanks a lot for your answer,
I am trying to compare in a similar way to your solution presented in: 
https://stackoverflow.com/questions/54713760/kafka-time-difference-last-two-records-ksql-or-other/58970040#58970040
But instead of comparing two integers like a temperature and adding them, I am trying to compare two strings. I have a sensor writing to a topic the current status of a machine and it is being actualized every 30 seconds. My idea is to write only new events with their corresponding information if the status of the machine has changed.
For example: 
i get something like: "Produktion", "Produktion", "Produktion"..."Produktion", "Blocked", "Blocked".... "Blocked", Available"
and it should look like: "Produktion", "Blocked", "Available"

As i am no programmer it gets very hard to do this with Kafka streams and the Processor API. If you have any ideas it would solve my Masterthesis 

Thanks

**Comment by rtrive** [comment]
is this problem solved? It will be useful to compare two records and made a difference between them. For example something like [this](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/difference/)
