### ISSUE TITLE
ksql standalone mode error 

### ISSUE THREAD

**Issue by pgibert** [confluentinc/ksql#290]
Hello  i a mrunning the example of pageviews . i dont have the same behaviour in the local mode and in the standalone mode .. did i miss something ?

**_$ bin/ksql-cli local_**
  .........

ksql> SELECT pageid FROM pageviews_original LIMIT 3;
Page_58
Page_30
Page_74
LIMIT reached for the partition.
Query terminated
ksql> exit
Exiting KSQL.
**$ cat./ksql-examples/src/main/resources/simpleQuery.sql**
SELECT pageid FROM pageviews_original LIMIT 3;
**_$ bin/ksql-cli standalone ./ksql-examples/src/main/resources/simpleQuery.sql_**
io.confluent.ksql.exception.ParseFailedException: _Parsing failed on KsqlEngine msg:PAGEVIEWS_ORIGINAL does not exist._
        at io.confluent.ksql.KsqlEngine.parseQueries(KsqlEngine.java:204)
        at io.confluent.ksql.cli.StandaloneExecutor.executeStatements(StandaloneExecutor.java:50)
        at io.confluent.ksql.cli.commands.Standalone.run(Standalone.java:74)

bestsR
phil

**Comment by hjafarpour** [comment]
Hi @pgibert.The error message in the standalone mode indicates that the source stream is not defined which is correct since the query file does not include CREATE statements. So you need to include CREATE statements in the beginning of your sql file for all source streams and table that you are using.
One more point, in the standalone mode you should not use SELECT statement. Instead you should use CREATE STREAM AS SELECT or CREATE TABLE AS SELECT so you will have the results in kafka topic.

**Comment by pgibert** [comment]
hello Hojjat , thanks .. :-)
