### ISSUE TITLE
Key while creating KSQL Stream

### ISSUE THREAD

**Issue by nvelvanore** [confluentinc/ksql#3006]
Can someone share your inputs/findings on the below cases:
    
    1) Is Key required on the Stream where you want to perform aggregate function. I have read several blogs and also recommendation from Confluent that KEY is required for aggregation function to work
    CREATE STREAM Employee \
      (EmpId BIGINT, \
       EmpName VARCHAR, \
       DeptId BIGINT,
       SAL BIGINT) \
     WITH (KAFKA_TOPIC='EmpTopic', \
           VALUE_FORMAT='JSON');
    	   
    While defining above Stream, I have not defined any KEY (ROWKEY is NULL). Underlying topic 'EmpTopic' also does not a KEY.
    
    I am performing aggregation function on the Stream.
    CREATE TABLE SALBYDEPT AS
    SELECT DeptId, \
             SUM(SAL) \
      FROM Employee 
      GROUP BY DeptId;
      
    Please confirm whether performing Aggregation function on the above Stream requires a KEY on 'Employee' stream ie NOT NULL ROWKEY on 'Employee' Stream
    
    2) As per Confluent documentation, "Windowing lets you control how to group records that have the same key for stateful operations, like aggregations or joins, into time spans. KSQL tracks windows per record key". Please help me understand the meaning of the above statement. Is it required the Stream should have NOT NULL KEY?
    
    CREATE STREAM test (location VARCHAR, parts INT ) WITH (VALUE_FORMAT='json', KAFKA_TOPIC='test');
    
    CREATE TABLE test_tbl AS SELECT
        location,
        SUM(parts) AS total
    FROM
        test
    WINDOW HOPPING (SIZE 10 MINUTES, ADVANCE BY 2 SECONDS)
    GROUP BY location;
    
    Topic 'test' and Stream 'test' have NULL ROWKEY value.I am performing WINDOW operation on the Stream which as NULL ROWKEY. Please confirm whether the above usage of WINDOW is valid with NULL ROWKEY?
    
    3) Will JOIN on Stream-Table retain the KEY
    CREATE TABLE users \
      (registertime BIGINT, \
       userid VARCHAR, \
       gender VARCHAR, \
       regionid VARCHAR) \
      WITH (KAFKA_TOPIC = 'users', \
            VALUE_FORMAT='JSON', \
            KEY = 'userid');
    		
    CREATE STREAM pageviews \
      (viewtime BIGINT, \
       userid VARCHAR, \
       pageid VARCHAR) \
      WITH (KAFKA_TOPIC='pageviews', \
            VALUE_FORMAT='DELIMITED', \
            KEY='pageid', \
            TIMESTAMP='viewtime');
    		
    CREATE STREAM pageviews_transformed as \
      SELECT viewtime, \
             userid, \
             pageid, \
             TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HH:mm:ss.SSS') AS timestring \
      FROM pageviews 
    		
    CREATE STREAM pageviews_enriched AS \
      SELECT pv.viewtime, \
             pv.userid AS userid, \
             pv.pageid, \
             pv.timestring, \
             u.gender, \
             u.regionid, \
             u.interests, \
             u.contactinfo \
      FROM pageviews_transformed pv \
      LEFT JOIN users u ON pv.userid = u.userid;
    	   
    Will JOIN on Stream-Table retain the 'UserId' as ROWKEY in the new Stream 'pageviews_enriched'
    
    4) I have seen several examples from Confluent on Github where Stream used in JOIN is not KEY'ed. But as per the documentation, Stream should have NOT NULL ROWKEY participating the JOIN. Please confirm to have NOT NULL ROWKEY in the Stream.
    
    Stream-Stream join and Stream-Table join. In the below example I am performing JOIN on Stream with NULL ROWKEY and Table. Is this valid?
    
    CREATE TABLE users \
      (registertime BIGINT, \
       userid VARCHAR, \
       gender VARCHAR, \
       regionid VARCHAR) \
      WITH (KAFKA_TOPIC = 'users', \
            VALUE_FORMAT='JSON', \
            KEY = 'userid');
    		
    CREATE STREAM pageviews \
      (viewtime BIGINT, \
       userid VARCHAR, \
       pageid VARCHAR) \
      WITH (KAFKA_TOPIC='pageviews', \
            VALUE_FORMAT='DELIMITED', \
            TIMESTAMP='viewtime');
    		
    CREATE STREAM pageviews_transformed as \
      SELECT viewtime, \
             userid, \
             pageid, \
             TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HH:mm:ss.SSS') AS timestring \
      FROM pageviews 
    		
    CREATE STREAM pageviews_enriched AS \
      SELECT pv.viewtime, \
             pv.userid AS userid, \
             pv.pageid, \
             pv.timestring, \
             u.gender, \
             u.regionid, \
             u.interests, \
             u.contactinfo \
      FROM pageviews_transformed pv \
      LEFT JOIN users u ON pv.userid = u.userid;

Regards,
Pradeep.

**Comment by big-andy-coates** [comment]
Hi Pardeep,

Let's work through your questions:

```
1) Is Key required on the Stream where you want to perform aggregate function. I have read several blogs and also recommendation from Confluent that KEY is required for aggregation function to work
CREATE STREAM Employee \
  (EmpId BIGINT, \
   EmpName VARCHAR, \
   DeptId BIGINT,
   SAL BIGINT) \
 WITH (KAFKA_TOPIC='EmpTopic', \
       VALUE_FORMAT='JSON');
	   
While defining above Stream, I have not defined any KEY (ROWKEY is NULL). Underlying topic 'EmpTopic' also does not a KEY.

I am performing aggregation function on the Stream.
CREATE TABLE SALBYDEPT AS
SELECT DeptId, \
         SUM(SAL) \
  FROM Employee 
  GROUP BY DeptId;
  
Please confirm whether performing Aggregation function on the above Stream requires a KEY on 'Employee' stream ie NOT NULL ROWKEY on 'Employee' Stream
```

The `KEY` in the `WITH` clause has always be optional for streams, and is optional for tables from v5.3 onwards.  The `KEY` identifies a field in the value schema that matches the data in the row's key.  This allows you to use the defined `KEY` field in your `GROUP BY` statement and KSQL will know it does not need to repartition your data.  

Your aggregate query above looks totally valid.  Your data does not have a key, so you shouldn't be setting `KEY` in the `WITH` clause. Under the hood KSQL is repartitioning your data, i.e. copying it across to an internal topic ending with `-repartition` with the `DeptId` copied into the key.  This is required as aggregations in KSQL are always done per-partition, so you need all items with the same GROUP BY key to be in the same partition in Kafka. 

However, if your data _did_ have a key and you wanted to group by that key, then you could run:

```sql
CREATE TABLE SALBYDEPT AS
SELECT SUM(SAL)
   FROM Employee 
  GROUP BY ROWKEY;
```

By grouping by `ROWKEY` tell KSQL it doesn't need to repartition the data to be able to aggregate.

If you had a copy of the key in the value, e.g. say the key and `DeptId` always matched, then you could define your `Employee` stream with `WITH(KEY='DeptId', ...)` and that would allow you to rewrite the above query as:

```sql
CREATE TABLE SALBYDEPT AS
SELECT DeptId, SUM(SAL)
   FROM Employee 
  GROUP BY DeptId;
```

And again, KSQL would know not to repartition the data.

```
2) As per Confluent documentation, "Windowing lets you control how to group records that have the same key for stateful operations, like aggregations or joins, into time spans. KSQL tracks windows per record key". Please help me understand the meaning of the above statement. Is it required the Stream should have NOT NULL KEY?

CREATE STREAM test (location VARCHAR, parts INT ) WITH (VALUE_FORMAT='json', KAFKA_TOPIC='test');

CREATE TABLE test_tbl AS SELECT
    location,
    SUM(parts) AS total
FROM
    test
WINDOW HOPPING (SIZE 10 MINUTES, ADVANCE BY 2 SECONDS)
GROUP BY location;

Topic 'test' and Stream 'test' have NULL ROWKEY value.I am performing WINDOW operation on the Stream which as NULL ROWKEY. Please confirm whether the above usage of WINDOW is valid with NULL ROWKEY?
```

Yes, the above use is valid. It is valid because the windowing is being done on the key that is produced by the `GROUP BY location`.  To put that another way, KSQL is first internally repartitioning your data by the GROUP BY clause, so the data _will_ now have a key and that key will store the data in `location`.  It is only _after_ the aggregation that KSQL is applying the windowing, i.e. the windowing is being applied to the `location` key.

```
3) Will JOIN on Stream-Table retain the KEY
CREATE TABLE users \
  (registertime BIGINT, \
   userid VARCHAR, \
   gender VARCHAR, \
   regionid VARCHAR) \
  WITH (KAFKA_TOPIC = 'users', \
        VALUE_FORMAT='JSON', \
        KEY = 'userid');
		
CREATE STREAM pageviews \
  (viewtime BIGINT, \
   userid VARCHAR, \
   pageid VARCHAR) \
  WITH (KAFKA_TOPIC='pageviews', \
        VALUE_FORMAT='DELIMITED', \
        KEY='pageid', \
        TIMESTAMP='viewtime');
		
CREATE STREAM pageviews_transformed as \
  SELECT viewtime, \
         userid, \
         pageid, \
         TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HH:mm:ss.SSS') AS timestring \
  FROM pageviews 
		
CREATE STREAM pageviews_enriched AS \
  SELECT pv.viewtime, \
         pv.userid AS userid, \
         pv.pageid, \
         pv.timestring, \
         u.gender, \
         u.regionid, \
         u.interests, \
         u.contactinfo \
  FROM pageviews_transformed pv \
  LEFT JOIN users u ON pv.userid = u.userid;
	   
Will JOIN on Stream-Table retain the 'UserId' as ROWKEY in the new Stream 'pageviews_enriched'
```

 The result of a join is always keyed on the join field. In this case this is indeed `userId`.  

Note: you may see strange join behaviour if the `UserId` field in `users` table does not match the key of the messages.  If that is the case then you should remove the `KEY` from the create table statement and change the above join to be `ON pv.userId = u.ROWKEY`.

```
4) I have seen several examples from Confluent on Github where Stream used in JOIN is not KEY'ed. But as per the documentation, Stream should have NOT NULL ROWKEY participating the JOIN. Please confirm to have NOT NULL ROWKEY in the Stream.

Stream-Stream join and Stream-Table join. In the below example I am performing JOIN on Stream with NULL ROWKEY and Table. Is this valid?

CREATE TABLE users \
  (registertime BIGINT, \
   userid VARCHAR, \
   gender VARCHAR, \
   regionid VARCHAR) \
  WITH (KAFKA_TOPIC = 'users', \
        VALUE_FORMAT='JSON', \
        KEY = 'userid');
		
CREATE STREAM pageviews \
  (viewtime BIGINT, \
   userid VARCHAR, \
   pageid VARCHAR) \
  WITH (KAFKA_TOPIC='pageviews', \
        VALUE_FORMAT='DELIMITED', \
        TIMESTAMP='viewtime');
		
CREATE STREAM pageviews_transformed as \
  SELECT viewtime, \
         userid, \
         pageid, \
         TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HH:mm:ss.SSS') AS timestring \
  FROM pageviews 
		
CREATE STREAM pageviews_enriched AS \
  SELECT pv.viewtime, \
         pv.userid AS userid, \
         pv.pageid, \
         pv.timestring, \
         u.gender, \
         u.regionid, \
         u.interests, \
         u.contactinfo \
  FROM pageviews_transformed pv \
  LEFT JOIN users u ON pv.userid = u.userid;
```

Joins are always performed upon the key of rows.  So a `null` key won't match anything in the join. However, in the examples above your streams may start out with a `null` key, but because you are joining on a field other than `ROWKEY`, KSQL will internally repartition your data for you so that it is repartitioned with the join field as the key.

More precisely, when you run:

```sql
CREATE STREAM pageviews_enriched AS \
  SELECT pv.viewtime, \
         pv.userid AS userid, \
         pv.pageid, \
         pv.timestring, \
         u.gender, \
         u.regionid, \
         u.interests, \
         u.contactinfo \
  FROM pageviews_transformed pv \
  LEFT JOIN users u ON pv.userid = u.userid;
```

KSQL sees that you want to join against `pageviews_transformed.userId` but the `userId` field is not the `KEY` field of the stream, so it will repartition the data in `pageviews_transformed` into a new topic, setting the key to match the value in `userId`.  

Hence the join is performed on a topic that _does_ have a key.

I hope this helps and thanks of using KSQL!

In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
