### ISSUE TITLE
Serialization Decimal value to JSON

### ISSUE THREAD

**Issue by millin** [confluentinc/ksql#3087]
KSQL ver: master branch (commit 2b5c3d1)

I have Avro topic with Decimal field that declared in schema as:
```
{
  "name": "coefficient",
  "type": [
    {
      "type": "bytes",
      "scale": 1,
      "precision": 4,
      "connect.version": 1,
      "connect.parameters": {
        "scale": "1",
        "connect.decimal.precision": "4"
      },
      "connect.default": "AA==",
      "connect.name": "org.apache.kafka.connect.data.Decimal",
      "logicalType": "decimal"
    },
    "null"
  ],
  "default": "\u0000"
}
```
I created STREAM with Avro formal:
```
CREATE STREAM AVRO_WITH_DECIMAL
 WITH (KAFKA_TOPIC='decimal_test', VALUE_FORMAT='AVRO');
```
And second STREAM to convert it to JSON:
```
CREATE STREAM JSON_WITH_DECIMAL
WITH (VALUE_FORMAT='JSON')
AS SELECT * FROM AVRO_WITH_DECIMAL;
```
In the resulting topic I see that decimal value not properly serialized to JSON:
```
... "COEFFICIENT":"ZA==", ...
```

**Comment by agavra** [comment]
Hello @millin - as it stands, we don't support Decimal in JSON because Kafka Connect uses HEX instead of numeric representation for decimal types. I have a KIP to allow us to serialize it as a number [KIP-481](https://cwiki.apache.org/confluence/display/KAFKA/KIP-481%3A+SerDe+Improvements+for+Connect+Decimal+type+in+JSON).
