### ISSUE TITLE
KSQL configuration not being supplied to UDF

### ISSUE THREAD

**Issue by jamezk** [confluentinc/ksql#3399]
I've created a configurable UDF and deployed the jar to the KSQL server but when I attempt to create a KSQL query that uses the query no configuration is passed to it.

I added an entry in my `ksql-server.properties` that I supply to KSQL server on startup:

`ksql.functions._global_.config.entries=matchA,matchB`

but the plugin `configure` method receives an empty map. I also tried naming the property as suggested with the lowercase name of the plugin included after `ksql.functions` but this does not work either.

I'm using Confluent 5.1.2.
Any help would be much appreciated.

**Comment by big-andy-coates** [comment]
Hi @jamezk,

I think you've run into a bug in earlier versions of KSQL:

https://github.com/confluentinc/ksql/issues/2586

This was fixed in 5.2:

https://github.com/confluentinc/ksql/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Abig-andy-coates+UDF

Apologies that you ran into this issue.

Andy
