### ISSUE TITLE
select * from misses case sensitive columns

### ISSUE THREAD

**Issue by smil2k** [confluentinc/ksql#3563]
create stream szamlak_corrected as select payload->szlaszam as iban, payload->ugyfelnev as "ugyfelnev" from szamlak partition by iban;

Renders the "ugyfelnev" column lower case.
Selecting from the stream using * the query returns nulls.

**Comment by smil2k** [comment]
KSQL Version: 5.3.1

**Comment by big-andy-coates** [comment]
Hi @smil2k 

I think you're running in to this bug: https://github.com/confluentinc/ksql/issues/1213, which is now fixed in the master branch and will be released soon in the 5.4 release.

It would be great if you could find the time to test your use case against the master branch to ensure you're issue is resolved.

In the interest of keeping our issue backlog tidy I'm going to close this issue as a duplicate. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
