### ISSUE TITLE
Pull queries: Http response should be json array containing all rows of result

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3571]
The http response returned by the \query REST endpoint should return one valid json object that contains an array of all rows in the query result.

**Comment by big-andy-coates** [comment]
Hey @vpapavas,

The `/query` endpoint is a websocket endpoint.  It sends back one row of results per websocket message. Each message is a free-standing, valid, JSON object. 

In many cases it is not possible to return 'one valid json object that contains an array of all rows' as its a potentially infinite number of rows being returned.  

It would also mean we couldn't send the first result until we also had the last.  This goes against the whole point for having the websocket endpoint.

I'm going to close this issue as invalid. If I've missed understood what you're proposing then please feel free to reopen with more info.

**Comment by vpapavas** [comment]
Hi @big-andy-coates ,

thank you for the reply. 

For pull queries, the results are finite and (for the foreseeable future) key lookups. It makes sense then for such queries to have a new endpoint that returns one http response comprising of one json array containing all the rows in the result. 

What do you think?

**Comment by MichaelDrogalis** [comment]
If we had two routes, we’d need clients to be smart enough to discern which is the right one to go to based on the query, right? That seems a bit tricky when we consider how this would work with JDBC in the future.

**Comment by big-andy-coates** [comment]
Pull queries don't use the `/query` websocket. They use  `/ksql` HTTP POST.  Responses are not streamed back (yet) but returned as a single JSON response containing all the rows.

However, in the future, as we extend the functionality of pull queries, we'll need to change the architecture of the rest server to allow KSQL to stream back chunked responses for pull queries, to allow it to stream back large result sets without needing to first build the full result in memory, (See https://github.com/confluentinc/ksql/issues/3575).

I _think_ what you might be alluding to in this issue is that the response you're getting back from the rest endpoint for pull queries may still be chunked.  Is this what you mean?

**Comment by MichaelDrogalis** [comment]
@big-andy-coates I'm asking about something a little different. Consider a pull query, like `select * from t where k=v`, and a push query, like `select * from t where k=v emit changes;`. The former would need to be sent to `/ksql`, and the latter would need to be sent to `/query`. So clients would need to be smart enough to make that distinction.

That might be totally fine for most clients, but I just want to make sure we're not painting ourselves into a corner when we support JDBC. AFAIK, all queries in JDBC go through the `executeQuery` method, so if we wanted to support push queries in JDBC, we might have a hard time doing that with this approach.

Maybe this isn't a real problem, but I just wanted to flag it.

**Comment by vpapavas** [comment]
For my use case, the `/ksql` endpoint that returns a single json object does exactly what I need. The documentation hasn't been updated so I though pull queries are going through `\query` as well. We can close the issue.

**Comment by big-andy-coates** [comment]
This was fixed when I moved pull queries to the /query endpoint.  The response is now an array of rows.
