### ISSUE TITLE
Drop support for using windowed sources as source for another query

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3984]
At the moment you can import windowed streams and tables using CS/CT commands, e.g. see https://github.com/confluentinc/ksql/blob/8cc913a0ae81212323016916c4be258d613bb27c/ksql-functional-tests/src/test/resources/query-validation-tests/session-windows.json#L36-L56

You can also build another windowed table on top of a windowed table.

Until [KIP-330](https://cwiki.apache.org/confluence/display/KAFKA/KIP-300%3A+Add+Windowed+KTable+API+in+StreamsBuilder) is done, this doesn't actually work most (any?) cases, because the statestore won't have eviction and will eventually fill up the disk and fail.

So... we should either: 
 a) Complete KIP-300, or
 b) Remove this functionality from KSQL:
     - ability to import (CT/CS) windowed sources 
           - likely no used much.
     - ability to use a windowed source as the input to another query
           - not sure how much this is used
           - there may be some simple operations that all permissible / possible, i.e. any that don't materialize the resulting KTable. e.g.
                  - table duplication: `CREATE TABLE AS SELECT * FROM WINDOWED_TABLE;`
                  - table filtering: `CREATE TABLE AS SELECT * FROM WINDOWED_TABLE WHERE x=y;`

**Comment by rodesai** [comment]
> there may be some simple operations that all permissible / possible, i.e. any that don't materialize the resulting KTable, e.g.
- table duplication: CREATE TABLE AS SELECT * FROM WINDOWED_TABLE;
- table filtering: CREATE TABLE AS SELECT * FROM WINDOWED_TABLE WHERE x=y;

I think the only operation that is possible is a projection. When you filter a table, you have to emit a tombstone for records that fail the filter so that any existing value is deleted. Streams will only do this if the source is loaded as a table (which is then materialized).

To implement a projection without an exploding state store, we'd have to load the windowed source table as a KStream. I'm not sure it's worth implementing this if KIP-330 is on the way. Probably better to just drop support for windowed source tables until we can use the new APIs from streams.

**Comment by rodesai** [comment]
https://github.com/confluentinc/ksql/pull/4244
