### ISSUE TITLE
(pull)-query a joined table

### ISSUE THREAD

**Issue by ShahOdin** [confluentinc/ksql#4493]
I have asked the question on stack-overflow: https://stackoverflow.com/questions/60123191/ksql-pull-query-a-joined-table

- Am I making a mistake? 
- Is the documentation unclear, or is it just me?

**Comment by ShahOdin** [comment]
@vpapavas @agavra could you please let me know if there is a workaround in the mean-time? Are pull queries not supported in the 0.5.x versions? I can see references to it all over the place and I am very confused as to why I can't seem to do it!

is it a problem with my streams/tables? is it a problem with the control center editor?

**Comment by mjsax** [comment]
Currently, ie, ksqlDB 0.6.0, only stream aggregation queries that return a table allow to query the result table.

For a table-table join, the result is not materialized into a local store, but only a changelog stream is produced and written to the result topic that corresponds to the result table.

**Comment by ShahOdin** [comment]
@mjsax Thanks. 

- I am testing with the latest version available on docker, namely 0.5.x

- I have the same problem on both tables and streams. All the combinations below.

  - table created out of kafka topic
  - stream created out of kafka topic
  - table created out of table-table join
  - stream created out of stream-stream join

fail to return pull queries.

**Comment by mjsax** [comment]
Thanks. I just double checked the KLIP. Seems, the backward compatibility was only done for _persistent_ queries, but not for _transient_ queries: https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-8-queryable-state-stores.md#backward-compatibility

**Comment by ShahOdin** [comment]
@mjsax Thanks. so what are the actions to take from this? and in the mean time, Is there a workaround for this? so I can present a demo to my team?

**Comment by ShahOdin** [comment]
@mjsax to clarify, 

- I was doing my tests with the `cp-all-in-one` [docker-compose file](https://github.com/confluentinc/examples/blob/master/cp-all-in-one/docker-compose.yml) , ie using: `confluentinc/cp-ksql-server:5.4.0`. 

- according to [this](https://github.com/confluentinc/ksql/issues/530#issuecomment-557214179) the point-in-time queries are now supported from `0.6.0` (at least some of them, when we take into account your comment above)

- By looking at above, I also noticed there exists an image called `confluentinc/ksqldb-server` which is now at version `0.7.0` which presumably supports the said feature.

- I think you misdiagnosed my problem but I am glad you spotted a missed feature.

- how do the two images `confluentinc/cp-ksql-server` and `confluentinc/ksqldb-server` differ, other than the supposed env-var setup for integration with the other `cp-x` components. shouldn't they be in sync?

- Is there an unofficial equivalent of `cp-all-in-one`'s [docker-compose file](https://github.com/confluentinc/examples/blob/master/cp-all-in-one/docker-compose.yml) that uses `confluentinc/ksqldb-server`? 

- The docker-compose file advertised on [ksqldb.io](https://ksqldb.io/quickstart.html) doesn't have schema-registry and connect integration which I would like to use at my demo. Can you help me put together a setup, consisting of at least: `[broker, zookeeper, schema-registry, connect]` but ideally a full-on `cp-all-in-one` setup where everything works together?

**Comment by mjsax** [comment]
Well, pull queries still have limitations. It's maybe too subtle in the docs but the example says:
```sql
SELECT select_expr [, ...]
  FROM aggregate_table
```

(1) pull queries over STREAMS (what you mention above as `stream created out of kafka topic` and `stream created out of stream-stream join`) do not really make sense to begin with, because a stream is stateless -- there is nothing to be queried.

(2) Atm, pull quries are only supported on TABLES that are the result of an _aggregation query_ (cf. above `FROM aggregate_table` -- I agree, it's quite subtle). The two types of tables you mentioned above (`table created out of kafka topic` and `table created out of table-table join`) are not yet queryable, because neither of both tables is actually materialized in a local state store, but only the result changelog topic is written into the corresponding output topic. It's a known (maybe not well documented) limitation that is still in 0.8.0 release (and it's unclear in which release it will be fixed atm).

**Comment by big-andy-coates** [comment]
This will be address by https://github.com/confluentinc/ksql/issues/5652. Closing this ticket as a duplicate.
