### ISSUE TITLE
Have a way to return all queries running in a KSQL cluster from a single cluster.

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#4603]
**Is your feature request related to a problem? Please describe.**
Users currently have to issue `SHOW QUERIES` to all nodes in a cluster in order to get an idea of what queries are running. This also leads to issues such as https://github.com/confluentinc/ksql/issues/4308#issuecomment-577359296

**Describe the solution you'd like**
A single server should be able to send requests to other servers in the cluster, collect the results from all of them, and then return that to the user.

Options for what the UX of this is

1.  Add an `ALL` modifier to `SHOW QUERIES` to indicate to ListQueriesExecutor to send requests to other nodes. The behavior of the two existing show queries command variants stay the same.
`SHOW QUERIES`
`SHOW ALL QUERIES`
`SHOW QUERIES EXTENDED`
`SHOW ALL QUERIES EXTENDED`

2. Make `SHOW QUERIES` and `SHOW QUERIES EXTENDED` cluster wide by default

**Comment by stevenpyzhang** [comment]
@big-andy-coates @rodesai thoughts on which UX would potentially be better?

**Comment by derekjn** [comment]
@stevenpyzhang thanks for writing this up. As we've discussed, I prefer taking option (2) to just make `SHOW QUERIES` cluster wide by default. I understand that this would be a breaking change but I still think it would be worth doing.

* I would expect `SHOW QUERIES` to return all queries so `SHOW ALL QUERIES` could be somewhat confusing.
* If KSQL is behind a load balancer, it could be confusing to get different results back across requests if `SHOW QUERIES` continues to operate at the local node level.
* Returning node-level query metadata isn't particularly useful because it excludes metadata associated with other nodes in the cluster. This seems to be what prompted this change in the first place.

Another option here would be to add host-level metadata to the current query status response so that the response doesn't break backward compatibility. Top-level status in this case would be the combined status across all nodes, which I believe is something we want here anyways.

```js
{
  "query_id": "id",
  "status": "RUNNING",
  // These are parallel lists
  "host_info": ["host1", "host2", ...]
  "host_status": ["RUNNING", "RUNNING", ...]
  ...
}
```

**Comment by stevenpyzhang** [comment]
@derekjn 
>Do we even have any other commands that operate on the local node?

`SHOW TABLES/STREAMS` are only run against the local node.
These could also be returning different results depending on which node services the request if one of the nodes is having issues processing the command topic and is lagging behind.

>{
  "query_id": "id",
  "status": "RUNNING",
  // These are parallel lists
  "host_info": ["host1", "host2", ...]
  "host_status": ["RUNNING", "RUNNING", ...]
  ...
}

I'm confused about what the "status" field would mean in this case. It looks like "host_status" would be coming from each instance of the query that's running and is fetched from that instance's streams application. Are we computing the "status" field ourselves based off of the host_status's?

**Comment by derekjn** [comment]
> SHOW TABLES/STREAMS are only run against the local node.

@stevenpyzhang gotcha, so in most cases these would be expected to return the same result assuming there are no issues or command topic lag.

> I'm confused about what the "status" field would mean in this case. 

This would be the cluster-wide query status, however we want to define that (e.g. one host down could mean the cluster-wide status is down, or any host being up could mean the cluster-wide status is up.
> Are we computing the "status" field ourselves based off of the host_status's?
This is just a sketch but that's the idea.

**Comment by stevenpyzhang** [comment]
@derekjn I think we're both in agreement about the approach to just make the default behavior of `SHOW QUERIES [EXTENDED]` multi-node by default. I'm still not entirely sure which response we should go with though.

a.
```
{
    {
        "query_id": "id",
        "status": "RUNNING",
                ...
        "host_info": <host1>
    },
    {
         "query_id": "id",
        "status": "RUNNING",
                ...
        "host_info": <host2>    
        
        
    }
}
```

b.
```
{
"query_id": "id",
"status": "RUNNING",
// These are parallel lists
"host_info": ["host1", "host2", ...]
"host_status": ["RUNNING", "RUNNING", ...]
...
}
```
cc @confluentinc/ksql any votes?

**Comment by agavra** [comment]
Would much prefer the option (a). The second gets really annoying to parse out and maintain indexes when iterating in the code base. I don't think we need to worry about performance and size overhead in this case so the one that is easier to parse and work with is probably better. We can also model (a) as a POJO.

**Comment by derekjn** [comment]
Agreed that option (a) would definitely be cleaner. @agavra the idea behind (b) was to leave existing keys in place so as to (mostly) not break backward compatibility. The main question to answer here is: are we ok with breaking backward compatibility for these responses?

While not ideal, I'm personally ok with it because I think cluster-wide results are "right" behavior. The surface area here probably isn't that large and status responses are largely independent of actual workloads.

**Comment by big-andy-coates** [comment]
Option a is going to get very verbose very quickly and put all the work on the clients to de-dup.  Can I suggest option c:

```
{
    {
        "query_id": "id1",
                ...
        "hosts": [
           "host1": "RUNNING",
           "host2": "RUNNING"
       ]
    },
    {
         "query_id": "id2",
                ...
        "hosts": [
           "host1": "RUNNING",
           "host3": "FAILED"
        ]
    }
}
```

**Comment by stevenpyzhang** [comment]
Finished in https://github.com/confluentinc/ksql/pull/4875
