### ISSUE TITLE
CommandRunner metric doesn't accurately report if the thread is running or not

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#4652]
**Describe the bug**
https://github.com/confluentinc/ksql/pull/4019 added a new metric for the CommandRunner thread. There's 4 scenarios that can happen to the thread.

1. The thread dies (metric should say Error)
2. The thread is still alive and polling the command topic for new records (metric should say Running)
3. The thread finds command topic records and processes them successfully (metric should say Running)
4. The thread finds records and gets stuck processing them (there's an infinite retry loop so it could get stuck forever) (metric should say Error)

This metric has trouble differentiating between scenario 1 and 2.

**To Reproduce**
Kill the CommandRunner thread while it's not executing a statement.

**Expected behavior**
The metric should transition to Error state

**Actual behaviour**
The metric stays in a Running state

**Additional context**
This happens because the metric only transitions to error state if it detects the CommandRunner is stuck processing a command. When no command is being processed, the metric will always be in a Running state.

**Comment by rodesai** [comment]
> 1. The thread dies

Honestly I can't think of a good reason for this to happen. We should either be retrying or the JVM should exit because we hit an uncaught exception. So to me the fix should be to ensure that this happens. That said, I vaguely remember some reasoning for not wanting to exit the JVM in this case, but I can't really think of it now. I don't buy a user running KSQL without some restart mechanism in place - there's no guarantee that the process will never exit.

**Comment by rodesai** [comment]
Never mind - now I remember - we currently don't handle the case where polling throws an exception. It's not safe to just retry the poll because we might skip events. So the thread would exit in this case and a user may not want to kill the process because their queries would stop processing (though I still think it's better to just restart in that case until we can deal with that error better).
