### ISSUE TITLE
ksqlDB creates Streams app for terminated queries when replaying command topic

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#4923]
**Describe the bug**

When replaying the command topic on restart in interactive mode, the ksqlDB server creates Streams app for all persistent query commands in the command topic, even for commands that have corresponding `TERMINATE` statements later in the command topic. From a correctness standpoint this is fine because the Streams apps are closed when the `TERMINATE` statement is processed, and therefore the Streams apps are never started, but this is a bug from a performance standpoint since we've seen that creating a Streams app can take ~ 2 seconds, which adds up when there are lots of terminated queries in the command topic.

**To Reproduce**

1. Start ksqlDB in interactive mode. (Definitely works on `master`, I think older versions as well.)
1. Run a persistent query.
1. Terminate the query.
1. Restart the server.

**Expected behavior**

The Streams app is never created.

**Actual behaviour**

Server logs show the Streams app for the query was created and then closed.

**Additional context**
 
As suggested by @rodesai :

> the fix should be simple - just store a `Supplier<KafkaStreams>` instead of `KafkaStreams` in `QueryMetadata` and only get it from `start()`

**Comment by big-andy-coates** [comment]
I've seen customers hitting issues related to this. e.g. 

1. User creates UDF
2. User creates stream/table using UDF
3. User drops stream/table
4. User removes or changes UDF so that SQL in step 2 now fails.
5. User restarts ksql..... and it won't restart.

The server fails to restart because its still trying to execute the SQL in the CREATE command added to the command topic in step 2.  This is bad!
