### ISSUE TITLE
Pre 0.7.0 tool to convert command topic to set of statements

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#4971]
Part of the migration guide to migrate from pre 0.7.0 to 0.7.0+ ksql requires replaying queries to a new command topic. It would be useful to have a script that compiled the list of old queries into a single file so that at least it would be easier to re-submit them to the new cluster after migrating the syntax.

**Comment by apurvam** [comment]
As for where the script should live, I'm thinking the `ksql/bin` folder of the source tree. If it's properly named then, it shouldn't create confusion. 

Thoughts @confluentinc/ksql @MichaelDrogalis @derekjn ?

**Comment by MichaelDrogalis** [comment]
I'm indifferent to where it lives. The main thing is that it's easily runnable, like we want the test runner to be. (e.g. can run `docker exec -it ksqldb-server tool-name`)

**Comment by derekjn** [comment]
@apurvam `ksql/bin` makes a lot of sense to me. I'm assuming it will be easy to install it on the Docker image's `PATH` if we do that.

@agavra in the packaging script, do we install all of the contents of `bin` on the `PATH`? Or do we need to explicitly handle this new file?

**Comment by agavra** [comment]
@derekjn yes we copy everything in bin

**Comment by derekjn** [comment]
That's great, so @MichaelDrogalis' example command will work transparently.

**Comment by big-andy-coates** [comment]
Why make this a script?  Why not make this a command you can run in KSQL?  A simple command you can run to dump the metastore to the console. Users can then spool this to a file.

IMHO, an inbuilt command, with documentation, is much better than some random script in a bin folder.

**Comment by MichaelDrogalis** [comment]
I'm not entirely sure of the reason, but the historical precedent for this is a separate tool. ([pgdump](https://www.postgresql.org/docs/9.3/app-pgdump.html) for Postgres, [mysqldump](https://dev.mysql.com/doc/refman/5.7/en/mysqldump-definition-data-dumps.html) for MySQL, [mongodump](https://docs.mongodb.com/manual/reference/program/mongodump/) for Mongo.)

**Comment by derekjn** [comment]
There are some tangible reasons why I think this makes sense as a separate utility:
* Over a long period of time, the dump utility can potentially end up having a lot of backward incompatibility management code. It's probably better to handle all of that special casing in a small, separate utility rather than in the core engine ([pg_dump version special casing](https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump.c#L2748)).
* With a separate utility it's easier to expose flags/options to give users a great deal of flexibility over the output behavior. In complex environments, fine tuning this behavior can be very helpful ([pg_dump options](https://www.postgresql.org/docs/12/app-pgdump.html)).
* It's easier to make a separate utility Unixy, i.e. composable with other commands.
* The query language is probably best used for describing desired query output. It can be tempting to pull a lot of adjacent operational functionality into the query language, but I think we should be mindful of where the line is between what belongs in the language and what should be a separate tool.

**Comment by vpapavas** [comment]
I think having the script available in a public place like along every release docs or migration guide or on the microsite, would be ideal. Then, users are not dependent on a docker image and it easier for us to also update the tool and make changes. What do you think? @agavra @apurvam @derekjn @MichaelDrogalis

**Comment by agavra** [comment]
I agree that having it available alongside the release docs is a good idea - but I'm happy with whatever people settle on

**Comment by apurvam** [comment]
As mentioned offline, a separate script serves the use case that people can download it and run it against an _old_ installation in preparation for migrating to a new version. I am not even sure what the mechanics would be for them to run a `DUMP` command from within the ksql CLI on an _older_ version of the command topic. 

I do agree that in the longer term, and internal command will be good, but it doesn't serve the migration use case as well IMO. So a nice to have would be to do the script so that the code can be reused. 

@vpapavas  what are the remaining blockers to get the tool released as a script?

**Comment by vpapavas** [comment]
I have a PR here: https://github.com/confluentinc/ksql/pull/5051 It will not get merged there, it's just for people to give feedback.

@apurvam What is left is to decide where on the webpage we want the script to be.

**Comment by MichaelDrogalis** [comment]
Seems like we should release this as a Pip package, right? We can make a dedicated page in the doc docs to explain what it is, then link to that docs page in the right places where people would find it useful.

**Comment by apurvam** [comment]
I am not to familiar with the overhead of distributing using pip. I think in practical terms, maybe creating an `extras` directory and putting it there until we decide the exact distribution vehicle might make sense. Basically, as 5.5 is released next week, having something downloadable to help with getting the list of queries would be better than nothing.

**Comment by derekjn** [comment]
I'm also in favor of just distributing this along with ksqlDB. If we use something like `pip`, that's another package we need to publish, own and maintain. I understand that this tool likely won't require much ongoing maintenance, but it's something to think about. I also think that distributing it with ksqlDB is more convenient for users. They can just directly run whatever example commands we provide without having to worry about ensuring that the tool is installed in their environment.

**Comment by MichaelDrogalis** [comment]
Both of those are fine - I just wanted to make sure we weren't going to drop the actual code into the docs/site or something. :)

**Comment by apurvam** [comment]
> I just wanted to make sure we weren't going to drop the actual code into the docs/site or something. :)

Absolutely :|

**Comment by spena** [comment]
The work for this tool is stopped and won't be available in future releases. Closing it.
