### ISSUE TITLE
/query-stream endpoint cannot serialize Struct

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#4996]
**Describe the bug**

The /query-stream endpoint fails to return rows containing Struct values.

**To Reproduce**

1. Start ksqlDB server from `master`
1. Create a test topic: `foo`
1. Create a stream with struct type: `create stream foo (s struct<f1 varchar>) with (kafka_topic='foo',value_format='json');`
1. Produce a record to the topic: `{"s":{"f1":"hello"}}`
1. Send request to /query-stream endpoint: `curl --http2 -X POST "http://localhost:8088/query-stream" -H "Content-Type: application/json; charset=utf-8" -d '{"sql":"select * from foo emit changes;","properties":{"auto.offset.reset":"earliest"}}'`

**Expected behavior**

Two JSON objects are returned: metadata and one row corresponding to the record in the stream.

**Actual behaviour**

A metadata object and an error are returned:
```
{"queryId":"954fe9ae-7bac-4bfc-8779-d40143333ec6","columnNames":["ROWTIME","ROWKEY","S"],"columnTypes":["BIGINT","STRING","STRUCT<`F1` STRING>"]}
{"status":"error","errorCode":100,"message":"Error in processing query"}
```

**Additional context**

The error is a serialization error: DelimitedQueryStreamResponseWriter#writeRow() fails in PojoCodec#serializeObject() with
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.kafka.connect.data.Struct and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.Collections$UnmodifiableRandomAccessList[8])
```

**Comment by purplefox** [comment]
I think this is probably because, the old API uses this mapper to serialize objects to the wire: https://github.com/confluentinc/ksql/blob/master/ksqldb-common/src/main/java/io/confluent/ksql/json/JsonMapper.java which has an extension for structs.
But in the new API in PojoCodec we currently use the default Vert.x mapper which doesn't have those extensions.
Possible solutions would be to a) Use the old API mapper for the new API too b) Add the extensions to  the Vert. mapper?
