### ISSUE TITLE
KSQL - drop topic

### ISSUE THREAD

**Issue by Lanayx** [confluentinc/ksql#510]
Is there a way to drop the topic from KSQL? According to [this file](https://github.com/confluentinc/ksql/blob/4.0.x/ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropTopicCommand.java) it is possible, and I tried  

```
DROP TOPIC my-topic 
DROP TOPIC "my-topic" 
DROP TOPIC 'my-topic' 
DROP TOPIC `my-topic`  

```
 But neither of this commands works. I get message   

```
Message 
-------------------------------------------------------------------------------  
io.confluent.ksql.util.KsqlException: No topic with name true was registered.

```

**Comment by hjafarpour** [comment]
@Lanayx KSQL topic is different concept than Kafka topic. KSQL topic is an internal concept for KSQL that represents a kafka topic along with metadata about that topic including  the topic format.
Since we do not expose KSQL topic externally you should not use it in KSQL statements.
If you wanna delete a kafka topic, you should delete it from kafka. In future we plan to add topic management capability to KSQL.

**Comment by datumgeek** [comment]
I found this guidance very helpful and related to your question:

	KSQL runs continuous queries. 
	They do not stop after you quit the CLI… 
	Maybe your queries are still running and re-create the topics?
	
```
	SHOW QUERIES;
	TERMINATE 'QUERY_ID';
```
