### ISSUE TITLE
Describe message format

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#515]
For Arcadia Data:

Need a way to discover the format of messages in a topic:
```sql
DESCRIBE TOPIC <topic_name> WITH (VALUE_FORMAT = 'JSON')
```

**Comment by hjafarpour** [comment]
@tomlinsonr Can you provide more details?

**Comment by miguno** [comment]
I got additional feedback offline:

> The use case here is that we want to see the event count in say, the last 30 seconds. Grouping by any column means we will then need to re-aggregate to get the total count. Plus for the user, it is not clear which column they need to re-aggregate on.
>
> Please permit aggregates without group bys, or permit group by on a literal string (which also doesn't work, or I could not figure out how to get working)

**Comment by miguno** [comment]
@tomlinsonr:  I suppose the motivation is data discovery, where, as a user, you might not know the data format of messages in a Kafka topic, and that's why you want KSQL to help you by auto-guessing the data format?

**Comment by tomlinsonr** [comment]
Yes that's correct. We are thinking from the perspective of the user creating the table (v.s the consumer of the data). They are likely to know the format of the data so they want to provide a hint to KSQL.

**Comment by apurvam** [comment]
@tomlinsonr ,  I am curious why your app needs to know the message format of the underlying topcis? What will you do with that through your KSQL query?

**Comment by miguno** [comment]
I think the bigger picture is:  A user wants to explore the available data in Kafka = explore what data resides in the various available topics.

1. In many cases, I'd argue that the user will not know the message format ahead of time.  Here, KSQL can help by trying to auto-guess the message format (e.g. attempt Avro first, then JSON, then DELIMITED etc.)
2. In some cases, the user already knows the message format of a topic because, for example, the same user is also writing data to that very same topic (hence prior knowledge of the topic's message format).

Case 2 is what @tomlinsonr is referring to.  And from what I understand he suggests that users in this scenario should be able to tell KSQL about the message format by giving a hint.

I think there are actually two different aspects to the bigger picture.

1. "Show me some data".  This goes into the direction of the current `PRINT`.  The point is to show, say, the 10 most recent messages in a topic just to get a first impression of what the *actual* data looks like.   Here, I'd argue that KSQL should auto-guess the format by default, and the user could optionally give a (value) format hint to override KSQL's auto-guess.
2. "Describe the structure of the topic to me".  This goes into the direction of `DESCRIBE`.  The point is to see which columns/fields (with associated types) exist in a topic, with the motivation to help you write a CS/CT statement to read this topic into a STREAM or TABLE, respectively.

@tomlinsonr : What do you think?  Could you share your feedback to my comments above and clarify what you are looking for?

**Comment by tomlinsonr** [comment]
@miguno is correct. We were focusing on (2) because it seemed like auto-guessing would be the bigger effort and we think (2) may be necessary anyway with (as an example) non-standard delimiters in DELIMITED files. We can also work to auto-guess on the client side by guessing multiple formats serially and seeing which one does not error out.

In show-me-some-data (1 above), auto-guessing would be great, along with an option to see the absolute raw data in the auto-guess in incorrect. Of course, specification of the format should be permitted in the case where the user knows. Showing the raw data would help the user specify that the DELIMITED format has a delimiter of "|", and not a delimiter of ","

The goal of the show-me-the-data is typically to understand what data is available, so that you can eventually build a model for the data and then build applications on that model. So show-me-some-data and describe-the-structure-of-the-topic are two parts of the same workflow. With both of these questions, the eventual motivation is to build a standard model of the data that can be queried.

**Comment by miguno** [comment]
@tomlinsonr: We recently added `PRINT TOPIC` support, which is essentially (1) above.  See https://www.confluent.io/blog/ksql-january-release-streaming-sql-apache-kafka/.

Work on (2) is not planned yet.

**Comment by tomlinsonr** [comment]
Thanks! Looks like this is exactly what we need.

**Comment by apurvam** [comment]
Sorry for being a bit late on this, but I am not clear if this issue should still be left open. With the `VALUE_FORMAT` hint, we can already parse and show you data in both json and avro formats in the `PRINT` statement.

With avro we also fetch the schema from the schema registry and show it to you with the `DESCRIBE` statement. 

Is there anything else you need here @tomlinsonr ?

**Comment by tomlinsonr** [comment]
I think PRINT give us most of what we need. Our goal is to build a UI that enables non-technical users to create tables and streams from topics for themselves via drag and drop. So our UI needs to understand the underlying schema from whatever files are in Kafka topics so we know what kind of CREATE TABLE statement to issue behind the scenes. If you can take care of the file parsing without any kind of hint from the user then even better. 

P.S. I take it PRINT works for delimited files also? Sorry. Haven’t had a chance to try it yet :)

**Comment by apurvam** [comment]
Yes. `PRINT` should work for delimited files. If it doesn't file a bug :) 

I am going to close this out since most of what you need is there. Dropping the hint may be much harder, and can be tracked as a separate enhancement if necessary.
