### ISSUE TITLE
Delete of a stream in 5.4.1 does not seem to clear data from topic command_topic.

### ISSUE THREAD

**Issue by kaushiksrinivas** [confluentinc/ksql#5275]
**Describe the bug**
We see a issue where in ksql is installed with 5.4.1 version.
A stream is created and deleted 'WITH TOPIC' as well. 
confirmed in kafka, the topic related to the stream is cleaned up.
Downgrade of the ksql software was done to 5.3.1
In this process, we still see the ksql upon boot in 5.3.1 software is trying to reference the deleted stream and is failing during de serializing with a column missing in the schema "useOffsetAsQueryID"

**To Reproduce**
Install 5.4.1
create a stream
delete the stream
downgrade to 5.3.1

**Expected behavior**
command topic to be completely cleared when the stream is deleted and should not have any stale data.

**Actual behaviour**
stream info is still persisted in the command topic even after the stream is being deleted.

**Additional context**

**Comment by kaushiksrinivas** [comment]
Is there anyone facing similar issue ? and any possible workarounds.

**Comment by stevenpyzhang** [comment]
The command topic contains all statements that need to be executed in order to reconstruct the internal state of the server. When you delete the stream, the create stream statement is still in the command topic, a drop statement is appended to the command topic and this is the statement that's executed by the server and deletes the stream. When a new server is started up, it'll execute both the create stream and then the drop stream statement, so this behavior you're seeing is expected.

The workaround here would be to delete the command topic when doing the downgrade. 5.4 command topic isn't backwards compatible with 5.3 server.

**Comment by kaushiksrinivas** [comment]
Is there any other work around which could possibly solve this rollback issue ?
like modifying the commands in the command topic to make it compatible with 5.3 server ?

**Comment by stevenpyzhang** [comment]
@kaushiksrinivas unfortunately, modifying the command topic like that isn't possible. We're treating the command topic as an immutable log currently. It's hard to say about upgrades from 5.3 and rollbacks to 5.3. We've been making a lot of breaking changes recently.

**Comment by kaushiksrinivas** [comment]
Hi @stevenpyzhang 
Would this command topic also impact the ksql in headless mode of operation ?

**Comment by stevenpyzhang** [comment]
headless mode KSQL doesn't use the command topic so this wouldn't be an issue there

**Comment by agavra** [comment]
I'm going to close this out as a question, until 1.0 for ksqlDB we are not guaranteeing forwards compatibility between versions
