### ISSUE TITLE
Processing log: deserialization errors for keys

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5627]
Currently, if a key fails to deserialize the message talks about the value format and probably includes the value in the `recordB64`.

e.g.

```
{
 "level": "ERROR",
 "logger": "processing.CSAS_S1_0.KsqlTopic.Source.deserializer",
 "time": 1592255634772,
 "message": {
   "type": 0,
   "deserializationError": {
     "errorMessage": "Error deserializing DELIMITED message from topic: ksql-test",
     "recordB64": "MTAw",
    "cause": [
      "Size of data received by IntegerDeserializer is not 4"
    ],
    "topic": "ksql-test"
  },
  "recordProcessingError": null,
  "productionError": null
}
```

We need: 
1. the `errorMessage` to make it clear if its a key or value deserialization error.
1. the `errorMessage` to talk about the key format when the key fails to deserialize.
1. the `recordB64` to be the serialized key when the key fails to deserialize.

**Comment by vcrfxia** [comment]
Had a look at this. Turns out the error messages that are thrown on deserialization errors are sane -- it's not the case that ksqlDB is always putting the value format into the error message, but there is a typo in the Kafka deserializer that explains the confusion in the example above: https://github.com/confluentinc/ksql/blob/94dac3d8339fc75bbfc5871047268b1f11b1bf42/ksqldb-serde/src/main/java/io/confluent/ksql/serde/kafka/KafkaSerdeFactory.java#L167

The record contents in the processing log message is the correct one (either key or value based on where the failure was), but there's nothing in the message itself to indicate whether the failure corresponds to the key or value. I've opened a PR to add a new field ("component" -- name subject to change) with value either "key" or "value" to indicate so. We can close this ticket once merged.
