### ISSUE TITLE
UDAFs throw NPEs when UDF metrics are enabled

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5890]
**Describe the bug**

Using ksqlDB 0.10.1 server + client:

When any UDAF is uploaded to ksqlDB and invoked with UDF metrics enabled, a NullPointerException is thrown by ksqlDB at `SELECT` time:

```
Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=s3, partition=0, offset=0, stacktrace=java.lang.NullPointerException
```

Steps to reproduce:

1. Follow the [how to create a user-defined function guide](https://docs.ksqldb.io/en/latest/how-to-guides/create-a-user-defined-function/#set-up-a-java-project). For the purposes of this issue, you only need to implement the aggregation `rolling_sum`.
2. Start ksqlDB [with JMX metrics enabled](https://docs.ksqldb.io/en/latest/operate-and-deploy/monitoring/), explicitly opting into UDF metrics by using the server config `ksql.udf.collect.metrics` set to `true`.
3. Follow the rest of the how-to guide. When you try to select with the aggregation, you'll encounter the NPE.

I'm not sure if it's related, but I did notice that no UDAFs, in-built or custom, show up in the JMX metrics.

**Comment by Ignis34Rus** [comment]
I've got the same problem and done a little investigation.
The problem lay in https://github.com/confluentinc/ksql/blob/07c135d18240276da8d9890ea1ba989ffde036b5/ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunction.java#L65
If metrics for UDF is enabled then on a first call to initMetrics all sensors will be created and assigned to UdafAggregateFunction class fields, but next time UdafAggregateFunction class is constructed call to initMetrics leave sensors fields with null value because sensors already created (so 'if (metrics.getSensor(...) == null)' block not executed) and there is no assigment of already created sensors to UdafAggregateFunction class fields.
And then we get
java.lang.NullPointerException at io.confluent.ksql.function.UdafAggregateFunction.timed(UdafAggregateFunction.java:182)
when UdafAggregateFunction.timed function is called

**Comment by big-andy-coates** [comment]
Thanks @Ignis34Rus  - that saved me some time! 👍
