### ISSUE TITLE
Add a `Since` field to function reference

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5900]
I'm seeing a lot of confusion in the community about what release certain functions are available in and which they are not.  Even I struggle, when answering stack overflow questions, to remember what version a specific function was introduced.

It would be AWESOME if we could update our function reference to include a `Since` field for each function, which indicates which version(s) it was introduced at.  I say versions, plural, as sometimes functions get back ported, so a function may be available in `0.11.0`, `0.10.1` and `0.9.4`.  It would be mislead to just use `0.9.4`.

Thoughts?

**Comment by agavra** [comment]
I agree, but just so you know what I do - every commit has which tags it is included in and then I look for the earliest. For example:
![image](https://user-images.githubusercontent.com/3172405/88847459-eb894780-d19b-11ea-99a4-543e583ee191.png)

**Comment by blueedgenick** [comment]
this is a great idea, big +1 from me. Perhaps we could incrementally get
started by just doing it for functions introduced in the "current" or
"in-progress" release(s) and set the precedent for always doing this when
adding new functions. Then work back through the last couple of releases
and add their corresponding "since" info to the docs too ?

**Comment by big-andy-coates** [comment]
I've added this
