### ISSUE TITLE
EMIT CHANGES in CTAS is required in docs but optional in actual    

### ISSUE THREAD

**Issue by golopot** [confluentinc/ksql#6167]
In the following snippet, the `EMIT CHANGES` clause can be omitted and the statement still executes successfully. While in docs the clause is required. Does the presence of `EMIT CHANGES` clause have any effect?

```sql
CREATE TABLE some_table
  AS SELECT
    id,
    SUM(v)
  FROM foo
  GROUP BY id
  EMIT CHANGES
```

**Versions**:
ksqldb-server:0.11.0
ksqldb-cli:0.11.0

**Comment by agavra** [comment]
Hello @golopot - to keep things backwards compatible, anytime you issue a `CREATE AS SELECT` the statement will implicitly add the `EMIT CHANGES` because we don't support creating materialized views off of pull queries.

If you were to issue the select query without the `CREATE TABLE some_table AS SELECT` the statement would not work:
```sql
-- fails without EMIT CHANGES
SELECT
    id,
    SUM(v)
  FROM foo
  GROUP BY id;
```
