### ISSUE TITLE
ksqlDB does not clear command futures map if a command transaction fails to commit

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#6340]
**Describe the bug**
ksqlDB does not clear command futures map if a command transaction fails to commit.

**Expected behavior**
A ksqlDB command may fail to commit. This might happen for a variety of not unexpected reasons: a transient issue between ksql and the broker, a conflicting command, etc. When this happens, a subsequent retry of the command should work fine (as long as it passes validation).

**Actual behaviour**
Instead, if the command fails to commit a subsequent retry will return the following error:
```
Could not write the statement '<statement>' into the command topic.
Caused by: Another command with the same id (<command id>) is being executed
```

**Proposed solution**
To fix this, we need to clean up the command from the futures map on a commit failure.

**Comment by mikhail193** [comment]
Any way to work around this? I have several commands in this state and now I cannot terminate several queries or drop several streams.

**Comment by jcustenborder** [comment]
@rodesai I can reproduce this pretty easily. When this has happened to me it's been a concurrency issue. I put together a terraform provider for KSQL. Due to the nature of terraform dependencies it will create resources in parallel if it can. In this case I see that it issues two DDL statements within a few milliseconds of each other. 

I'm also seeing this error message. 
```
The producer has been rejected from the broker because it tried to use an old epoch with the transactionalId
```
