### ISSUE TITLE
latest_by_offset does not properly handle nulls with session windows

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#6557]
**Describe the bug**
`latest_by_offset` does not properly ignore `null` values when session windows are used in the aggregation query. A `null` value can be returned in this case. Other types of windows and non-windowed aggregations work fine.

**To Reproduce**
ksqlDB versions: 6.0.0, 0.12.0

```sql
create stream s (f1 string, f2 string) with (kafka_topic='s', value_format='json', partitions=1);

--Insert record with non-null field to be aggregated with latest_by_offset
insert into s (f1, f2) values ('a', 'v1');

--Works fine
select f1, latest_by_offset(f2) from s window session(10 minutes) group by f1 emit changes;
+-------------------------------------------------------------+-------------------------------------------------------------+
|F1                                                           |KSQL_COL_0                                                   |
+-------------------------------------------------------------+-------------------------------------------------------------+
|a                                                            |v1                                                           |
Query terminated

--Insert new record with null value for field f2
insert into s (f1) values ('a');

--null is returned for the aggregate value, instead of v1 as expected - this is the bug
select f1, latest_by_offset(f2) from s window session(10 minutes) group by f1 emit changes;
+-------------------------------------------------------------+-------------------------------------------------------------+
|F1                                                           |KSQL_COL_0                                                   |
+-------------------------------------------------------------+-------------------------------------------------------------+
|a                                                            |null                                                         |
Query terminated

--Works fine for other types of windows
select f1, latest_by_offset(f2) from s window tumbling(size 10 minutes) group by f1 emit changes;
+-------------------------------------------------------------+-------------------------------------------------------------+
|F1                                                           |KSQL_COL_0                                                   |
+-------------------------------------------------------------+-------------------------------------------------------------+
|a                                                            |v1                                                           |
Query terminated
```

**Expected behavior**
In the example above, value `v1` should be returned from the session-window aggregate query, instead of `null`

**Actual behaviour**
`null` is returned from the session-window aggregate, instead of being ignored.

**Additional context**
Problem appears to be a bug in the `merge` method.

**Comment by vpapavas** [comment]
I am not sure if this should be classified as a bug of KSQL as it seems it depends on how streams handles session windows. For the tumbling window, there is only one window and both records belong to that window hence there is no merge called when aggregating. 
For the session window, since each key (even the same one) is a different session, during computation the two sessions are merged into one and the merge of the aggregator is called. 
Now, the merge of the aggregator for `latest_by_offset` just keeps the latest value which in our case is `null`.

**Comment by blueedgenick** [comment]
isn't there some "semantic confusion" to this ? i know it's an age-old question as to whether NULL is "a value" in SQL or not (sometimes it is, and sometimes it isn't, depending on the context). I suspect that some confusion arises here because of the nature of the particular aggregate function, `latest_by_offset`, which is mixing kafka-messaging semantics into SQL ones. To see what I mean, try explaining the situation to yourself with a different aggregate - say a `COUNT` - and ask what we think the desired behavior should be...can you COUNT a null-valued column ? (I suspect the answer is that the count would not be incremented for a NULL but i'd have to go check that). My point being that we should try to be consistent across all aggregates in terms of their NULL behaviors, rather than concluding that, because the NULL came in on a kafka message with a higher offset, it _must_ be the case that it should be included in the aggregate computation (or not).  Ideally, wouldn't all aggregate functions treat incoming NULLs the same way, regardless of which function or windowing type ?
