### ISSUE TITLE
Remove collection size limit for COLLECT_SET/LIST 

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#6711]
Currently `COLLECT_LIST` and `COLLECT_SET` are limited to maintaining `1000` items. Any additions to these collections beyond this limit will be silently ignored, which can be confusing for users. We should remove this hard limit entirely, and introduce function-level configuration parameters for environments that need to enforce a hard limit on collection sizes.

**Comment by scottadav** [comment]
One of our tables that we want to COLLECT_LIST/COLLECT_SET with has >100,000 elements. This will prohibit use of KSQLDB. We will continue to use Kafka Streams.

**Comment by vpapavas** [comment]
I don't think we should remove the hard limit as it can seriously destabilize ksqlDB. We can make it configurable but again, it's risky.

**Comment by derekjn** [comment]
> I don't think we should remove the hard limit as it can seriously destabilize ksqlDB. We can make it configurable but again, it's risky.

As long as we're clear in the docs about the perf/stability implications around maintaining large collections then I think it's worth removing this hard limit. We can even keep the current limit of `1000` as the default function-level config for these functions, so if anyone wants to raise it they'd be doing so intentionally and at their own risk. But as it stands, these functions aren't usable for serious workloads IMO.

**Comment by MichaelDrogalis** [comment]
There are two really negative consequences to the limit and behavior we have today:

1. As Derek said, a cap of 1K is unable for a significant number of workloads. Besides, how many people absolutely know what the upper limit of their key count will be?
2. The behavior when you crest 1K (silent discarding) is completely bemusing and gives you no recourse to change it.

I think it makes the most sense to remove the cap because it solves for both of those points at the same time. It's obviously not great that you can exhaust memory by default, but this comes back to something that we talk about a lot: in ksqlDB (and all databases) you do adversarial things that will crush your resources. This isn't a new trade-off. We should eventually solve this with something like anti-caching of state, but we needed to do that anyway.

We'd obviously want to set a cap for workloads that run in Confluent Cloud. But as an aside, the figure 1K for that runtime is specious. It probably ought to be higher there.

**Comment by agavra** [comment]
This isn't as trivial as it seems at face-level. Our UDAF framework does not currently have any way to configure UDAFs independently (like our UDFs have, by implementing `Configurable`). 

My LOE estimate would be about 1 week of engineering time to ship this feature.

**Comment by MichaelDrogalis** [comment]
Related: https://github.com/confluentinc/ksql/issues/5738, https://github.com/confluentinc/ksql/issues/5737
