### ISSUE TITLE
A question about a proper way of writing tests and ksql-functional-tests module

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#6747]
ksqldb-server (docker image) version: 0.13.0
ksqldb-api-client (java library) version: 0.13.0
I'm writing a spring boot application that uses ksql and I'm initializing all my streams and tables with Client.executeStatement.
I want to write tests for my ksql but I don't want to use ksql-test-runner and maintain separate ksql statements files and java classes that create streams, so I thought about using  [KsqlTestingTool.java](https://github.com/confluentinc/ksql/blob/0.13.0-ksqldb/ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/KsqlTestingTool.java) logic from ksql-functional-tests module, but I'm not able to find 0.13.0 version of it anywhere on Maven, the latest version is 5.4 or 0.7.1 (I don't understand the difference between 0.X versions and 5.X, 6.X versions of ksqldb either, so clarification would be appreciated).
Does anyone know if this library is somewhere in maven ?
I had to use "https://ksqldb-maven.s3.amazonaws.com/" to get ksqldb-api-client in 0.13.0 version, so maybe it's somewhere there ?
Specifically, I'd like to reuse this code for my tests and run it with junit runner:
```
  final TestCaseNode testCaseNode = new TestCaseNode(
        "KSQL_Test",
        Optional.empty(),
        null,
        (inputFile == null) ? null : inputRecordNodes.getInputRecords(),
        outRecordNodes.getOutputRecords(),
        Collections.emptyList(),
        statements,
        null,
        null,
        null,
        true
    );

    final PathLocation location = new PathLocation(stmtsPath.toAbsolutePath());

    final TestCase testCase = TestCaseBuilder
        .buildTests(testCaseNode, location.getTestPath(), name -> location)
        .get(0);

    executeTestCase(
        testCase,
        TestExecutor.create(extensionDir));
```

Thanks in advance!

**Comment by agavra** [comment]
Thanks for reaching out @maksymilian-gasztych - a few comments:

- Feel free to depend directly on internal classes like `KsqlTestingTool.java`, but keep in mind that we don't make any guarantees about those classes as far as compatibility across versions go. At some point, we may decide to remove it altogether.
- If you can only find 5.4/0.7.1 my guess is that you're looking for it under the old `ksql-functional-tests` module instead of the `ksqldb-functional-tests` (ksql was renamed and repackaged as ksqlDB after 5.4). This ties into your question about the versioning differences. The `0.x.x` versions are the community releases of ksqlDB and the `5.x.x`/`6.x.x` versions are the confluent platform distributions. You can see the version lineups here: https://docs.confluent.io/platform/current/installation/versions-interoperability.html#ksqldb (note that the community versions are released more often, but with less cross-testing with other CP components).
- I'm not entirely sure what we publish to https://ksqldb-maven.s3.amazonaws.com/ - that might just be jars that we intended to be for public consumption (e.g. the udf jars and the client jars)

Hopefully I'll get some time to look into this more in the coming days, but let me know if that unblocked you.

**Comment by maksymilian-gasztych** [comment]
That helped a lot, than you. seems I was looking for `ksql-functional-tests` as you mentioned. We haven't choosen yet if we want to host our own ksqldb-server or use confluent cloud, but we're leaning towards the cloud solution. From what you're saying it seems that they're compatible so no isues with that and we can decide later.
Thank you once again!

**Comment by maksymilian-gasztych** [comment]
@agavra 
Thanks to You I managed to write a simple library to help us write tests in Kotlin. Just letting you know how the usage looks like if you're interested. That kind of tests might be also useful to other people, so maybe you could consider including it into the tests package ? 
```
// source streams and tables are created from input classes based on name : ClassNameStream = CREATE STREAM CLASS_NAME_STREAM (properties based on class properties) WITH(kafka_topic='CLASS_NAME_STREAM')
data class OrdersStream(val id: Int,val orderUnits: Double)
data class Result(val id:Int,val orderUnits: Double,val caseResult: String)

class KsqldbKotlinTest {

    @Test
    fun runTest() {

        val inputs = listOf(OrdersStream(0,2.0))

        val outputs = listOf(Result(0,2.0,"medium"))

        val statements = listOf("CREATE STREAM result AS SELECT ID, order_units, CASE WHEN order_units < 2.0 THEN 'small'" +
                " WHEN order_units < 4.0 THEN 'medium' ELSE 'large' END AS case_result FROM orders_stream;")

        runKsqlTest(inputs,statements,outputs)
    }

}
```

**Comment by agavra** [comment]
This is super cool @maksymilian-gasztych! cc @colinhicks - I think it might be valuable at some point to expand our java/kotlin testing framework; in the short-term we're trying to build tools that target developers who aren't very proficient in Java.

If you're interested in where we wanted to take the testing functionality going forward, we're thinking of going down the lines of making it even more "sql-y". See https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-32-sql-testing-tool.md for the vision and here's an example of it being used: https://github.com/confluentinc/ksql/blob/master/ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql

I'll definitely consider making the top level class easy to integrate with java-only testing.
