### ISSUE TITLE
Only the failed SQL statement should be displayed in the CLI instead of all the executed statements

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#6850]
**Is your feature request related to a problem? Please describe.**
When executing a list of statements in one batch in the server, if one of the statements fail, the server returns all the statements that are in the batch and not only the statement that fail. This is not a problem for a few statements. However, if a user uses a SQL script with several statements, then they'll see a verbose error in the client result.

i.e.

I have a file with two statements (the create will fail with a syntax error):
```
$ cat /tmp/test.sql 
drop stream if exists s1;
create stream if not exist s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);
```
When I execute the above file, I get the following error:
```
$ ./ksql --file /tmp/test.sql
line 2:8: no viable alternative at input 'create if'
Statement: drop stream if exists s1;
create if not exists stream s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);
Caused by: line 2:8: no viable alternative at input 'create stream if not exist'
Caused by: org.antlr.v4.runtime.NoViableAltException
```

or take this another example with the same statements but using the CLI `-e` parameter:
```
./ksql -e "drop stream if exists s1; create stream if not exist s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);"
line 1:48: no viable alternative at input 'create stream if not exist'
Statement: drop stream if exists s1; create stream if not exist s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);
Caused by: line 1:48: no viable alternative at input 'create stream if not exist'
Caused by: org.antlr.v4.runtime.NoViableAltException
```

The error shows the right error in the first line, but it then displays all the statements again. If a user has 30 statements, then this line will be too large.

**Describe the solution you'd like**
The error should only include the failed statement, not all of them.

i.e.
```
./ksql -e "drop stream if exists s1; create stream if not exist s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);"
line 1:48: no viable alternative at input 'create stream if not exist'
Statement: create stream if not exist s1(id int) with (kafka_topic='s1', value_format='json', partitions=1);
Caused by: line 1:48: no viable alternative at input 'create stream if not exist'
Caused by: org.antlr.v4.runtime.NoViableAltException
```

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by Gerrrr** [comment]
I spent a couple of hours on this issue today; here is a quick status update.

## RCA

This issue happens in `DefaultKSQLParser` on the CLI side here:

https://github.com/confluentinc/ksql/blob/4275a42a6e59c76a7a2fb98044b5b19a34ca57b4/ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java#L428-L429

Printing all statements from a file rather than only the failing statement is a side effect of passing the entire file into `handleLine`:

https://github.com/confluentinc/ksql/blob/4275a42a6e59c76a7a2fb98044b5b19a34ca57b4/ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java#L228-L231

TBC the issue happens during parsing before the `SqlBaseParser.StatementsContext` is built.

## Ideas

There are 2 options to explore:
1. Make the parser work correctly with multiple statements in a single string. One way to do that is to split parsing into 2 steps - splitting statements from each other and then parsing them individually. This way, if a statement has syntax issues, we can return only that one.
2. The `runScript` comments mention a previous solution to executing statements from a file that was removed in https://github.com/confluentinc/ksql/pull/6551. I quickly tried reverting that, and it turns out that `RunScript` does not suffer from the issue we are trying to fix here. Consequently, another option is to add support for `PRINT/SELECT` without overriding variables/CLI properties to `RunScript`. 

TBH I haven't looked too much into option 2 yet, but it seems more promising to me from the outcome POV. Option 1 introduces a lot of complications as well as potential performance issues in parsing for just this one use case.

/cc @spena
