### ISSUE TITLE
Seems that the latest 0.15.0 version artifacts have not been pushed to the maven repository

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7021]
Hi, the documentation was updated after the 0.15.0 release, but the artifacts cannot be found.
https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/java-client/#tutorial-examples

Hopefully that can be fixed quickly!

![image](https://user-images.githubusercontent.com/72374203/108291118-0fae8380-71d5-11eb-805f-e939b453085f.png)

Thank you!

**Comment by vcrfxia** [comment]
Hi @maksymilian-gasztych , the 0.15.0 maven artifacts were already available last night (after this issue was filed) but in confirming that was the case I discovered a mistake in one of the dependency repos which might explain any import issues you were seeing. (The dependency issue has been corrected in https://github.com/confluentinc/ksql/pull/7024.) Can you try again?

**Comment by maksymilian-gasztych** [comment]
@vcrfxia Hi,
 looks good now! I appreciate your prompt response!

**Comment by vcrfxia** [comment]
Wonderful. Thanks for confirming, and for raising this in the first place!
