### ISSUE TITLE
Inconsistent handling of NULL values

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#7065]
Given a stream `s1` that contains a `NULL` value:

```sql
CREATE STREAM s1 (x INTEGER) ...
INSERT INTO s1 (x) VALUES (null);
```
If that `NULL` expression is used in an arithmetic operation, the result of the operation will be `NULL`:
```sql
SELECT x + 1 FROM s1 EMIT CHANGES;
```
However, if a `NULL` literal is used in the same way, an NPE will be thrown:
```
ksql> SELECT NULL + 1 FROM s1 EMIT CHANGES;
java.lang.NullPointerException
```
We should make `NULL` handling consistent regardless of context, as some users will evaluate ksqlDB's `NULL` handling by testing a simple example using a `NULL` literal like the one above. Any assumptions they derive from such tests will currently not be valid for actual queries.

**Comment by stevenpyzhang** [comment]
`select ARRAY[value0+5, 1+5], ARRAY[1+5], value0 + 5 from TEST emit changes;`
If value0 is null in a record, then the output is null, [6], null. This seems a bit strange since it seems like the first array should be `[null, 6]`

`select ARRAY[ucase(value0), 'test'] from TEST1 emit changes;`  returns [null, 'test']

It seems like if there's a NPE thrown in the expression when the query is processing, the corresponding select column gets a null value. The NPE thrown before the query is created/executed is because of our type checking of the expression before we create the query which fails.

**Comment by cprasad1** [comment]
We got rid of the NPE, and we now give a new error message in such cases. See the description of https://github.com/confluentinc/ksql/pull/7554 for more details. I am closing this issue, and I have created this issue https://github.com/confluentinc/ksql/issues/7602 instead since the scope of feature that we want is much larger.
