### ISSUE TITLE
Changing KEY_FORMAT doesn't work in CTAS with GROUP BY STRUCT

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#7242]
**Describe the bug**
Using `WITH (KEY_FORMAT='<format>')` seems to be ignored in an aggregation CTAS that performs a `GROUP BY` on a `STRUCT`, when the source stream has `KEY_FORMAT='KAFKA'` (the default).

**To Reproduce**
Version: 0.15.0

```sql
create stream s (f1 string, f2 string, f3 string) with (kafka_topic='s', value_format='json', partitions=1);

create table t with (key_format='json') as select struct(f1:=f1, f2:=f2) as k, as_value(struct(f1:=f1, f2:=f2)) as key, count(*) as total from s group by struct(f1:=f1, f2:=f2);
```

**Expected behavior**
Table successfully created with JSON key struct.

**Actual behaviour**
```
Key format does not support schema.
format: KAFKA
schema: Persistence{columns=[`KSQL_COL_0` STRUCT<`F1` STRING, `F2` STRING> KEY], features=[]}
reason: The 'KAFKA' format does not support type 'STRUCT'
Caused by: The 'KAFKA' format does not support type 'STRUCT'
```

**Additional context**
```sql
--Works fine for CTAS with multiple individual fields instead of a STRUCT
create table t1 with (key_format='json') as select f1, f2, as_value(f1) as f1v, as_value(f2) as f2v, count(*) as cnt from s group by f1, f2;

---Also works with CSAS using a STRUCT key
create stream s1 with (key_format='json') as select struct(f1:=f1, f2:=f2) as k, as_value(struct(f1:=f1, f2:=f2)) as key from s partition by struct(f1:=f1, f2:=f2); 
```

**Comment by vcrfxia** [comment]
Slight clarification on this bug: the bug is only present when converting from a key format that does not support structs (e.g., the `KAFKA` format) to a key format that does support structs (e.g., `JSON`). Until this bug is fixed, a workaround is to copy the source stream into another stream with a key format that supports structs, and then run the aggregation query to create the table.
