### ISSUE TITLE
Anyway to handle continuous streams join?

### ISSUE THREAD

**Issue by vishwajeets7** [confluentinc/ksql#7380]
I have created two streams A (Id) & B (Id, Account), both these streams are receiving data from DB2 based on update transactions.

I am joining A & B streams based on Id to a KTable,
KTable is pouring the joined data to Kafka topic

Use case:
When streams receive the data in random order, example Id = 1 could be updated multiple times, which triggers join and updates the KTable each time.
So every time KTable is updated it updates the Kafka topic & so the subscribe consumer services.

Kafka topic receives data as:
Id     Accounts
1      A1
1      A1, B1

Looking for solution if the streams join can possibly produce the complete join (maybe with some stream completed event) and then update the KTable.

So output would be only one row per Id:
Id     Accounts
1      A1, B1

**Comment by maksymilian-gasztych** [comment]
Your question is a little to chaotic to understand well, but from what I gather you can just use windowed stream join first
`select * from stream_a join stream_b within 10 minutes on ... `etc, this will produce only one record if there is only one update each to the joined streams. Then you can join with your table. 
You need to also set ksqldb to exactly_once semantic so in case of failure records are not duplicated, so I think you should try to revisit your system design.

**Comment by vishwajeets7** [comment]
maybe missed to include, the window of 60 seconds is already added to my join query. 
Issue is the stream is receiving same ID multiple times, so every time the join is triggered the KTable receives the update which in turn updates the Kafka Topic.

when join is hit first time:
ID         Account
1          A1

Topic is updated with ID=1, Account = A1.

If the ID = 1 is received in the same window the join triggers again, which causes the Kafka topic to be updated with ID=1, Account = B1

Looking for a solution if  the join can differ the results till window is complete.

**Comment by mjsax** [comment]
Not sure if I understand the question: Could you maybe provide a simple example that shows data from both input topics (A and B), and also shows the result you want to get in the output topic?

> I have created two streams A (Id) & B (Id, Account), both these streams are receiving data from DB2 based on update transactions.

Based on this statement, it sound like as if you should read both inputs as a TABLE an do a table-table join. Not sure, why you would need to read an input as STREAM, or why you would need a window...

**Comment by vishwajeets7** [comment]
@mjsax  Thanks for your response.

Stream A is associated with DB2 table and holds ID information
Stream B is associated with another DB2 table and holds Account information

Stream A:
ID
----
1
2
3
...

Stream B (one to many):
ID       Account
-----------------
1        A1
2        B1
3        C1
1        B2

I am creating a table with the stream joins (with a window 60 seconds), as these are real time updates, ID = 1 is updated in the table twice so the Kafka topic gets updated with two messages:
- {Id=1, Account=A1}
- {Id=1, Account=B2}

The KTable shows the records as correct:
ID         Account
-------------------
1          A1, B2
2          B1
3          C1

However the Kafka topic is showing four messages (topic is associated with the table), think the reason is ID=1 is updated in the table twice (as stream is continuous event log).

**Comment by mjsax** [comment]
Not sure if I can follow:

> The KTable shows the records as correct

What do you mean by this?

> However the Kafka topic is showing four messages

What messages?

Also, what query to do actually issue?

**Comment by vishwajeets7** [comment]
@mjsax, please refer to the examples with data included.

Stepping out the concern:
1. Stream join is triggered multiple times for ID=1, (stream A, stream B)
2. the KTable holding the output of the join is showing 3 records. (refer the example data)
3. KTable is linked to a Kafka topic 
4. Kafka topic shows 4 messages, shows twice ID=1

Let me know which step is not understood.

Thanks.

**Comment by mjsax** [comment]
Let me try to rephrase (and clear some terminology, as some terms are overloaded and need clear definitions).

- a Kafka topic
- a STREAM (basically a schema definition over a topic, including assigned semantics to be an event stream)
- a TABLE (basically a schema definition over a topic, including assigned semantics to be an changelog stream; plus for some TABLEs a RocksDB state store that store the latest version per key)

I try to avoid the term "stream" (in lower cases) because it's a very generic term. All three of the above could be called a "stream".

As you say that "stream A" and "stream B" are associated with a DB2 table (I assume you have some upstream CDB pipeline that write a DB changelog into a topic), you should create a TABLE for each topic (not a STREAM). However, I am not sure what you did. Especially, because you say you use a window of 60 seconds, and only STREAM-STREAM joins are windowed.

Also the sentence "am creating a table with the stream joins" does not make sense, because if you join two STREAMs, the result is a STREAM, not a TABLE. Or are you saying that you are taking the result of the STREAM-STREAM join and perform some aggregation to get a final result TABLE?

So it seem that the input of topic A is `1 ; 2 ; 3 ; 4` and that the input of topic B is `1-A1 ; 2-B1 ; 3-C1 ; 1-B2`. But when you say that the `KTable` (not sure why use use the term `KTable` -- in ksqlDB there are STREAMS and TABLES; `KTable` is used in Kafka Streams only; or are you actually using Kafka Stream but not ksqlDB?) show record `1-A1,B2 ; 2-B1 ; 3-C1` what do you exactly mean? Do you refer to RocksDB? How do you read the content (via pull queries?). When you say "Kafka topic shows 4 messages" can you let us know what 4 messages?

It's still a little unclear what you actually do. If you could share the queries and explain in detail if you work with STREAMs or TABLEs it would be easier.

And I guess an upfront answer will be "yes", the output of a TABLE result may contain multiple entries for the same key, because the output topic stores the changelog of the result TABLE. In ksqlDB there is nothing like a "snapshot", because ksqlDB is about stream processing.

**Comment by mjsax** [comment]
> TABE A has one column ID with row values 1,2,3,4 and TABLE B has two columns ID & ACCOUNT with row & column (ID - ACCOUNT) values 1-A1 ; 2-B1 ; 3-C1 ; 1-B2. Notice ID 1 is repeated with different ACCOUNT values (A1 and B2)

If you have a TABLE B with primary key ID, the TABLE **snapshot** (ie, RocksDB) cannot contain two rows with ID=1 -- If you issue `SELECT * FROM b WHERE ID=1` it will return only one value (RocksDB is not able to store two key-value pairs with the same key) -- if you issue a different query, ie, `SELECT * FROM b WHERE ID=1 EMIT CHANGES` you don't query the TABLE **snapshot** but the **changelog** and for this case, you can of course get multiple update record for the same key.

Note that a TABLE is ksqlDB is always a hybrid: there is the underlying changelog stored in the topic, plus a snapshot stored in RocksDB. (Thus, when you say TABLE, you always need to clarify if you talk about the changelog or the snapshot... Otherwise it's ambiguous what you mean.)

> However the updates in a TABLE are summarized in 3 rows

For the **snapshot** of the result table, yes, but not for its **changelog**.

> expecting to get the summarized output for KAFKA TOPIC.

and 
> As the STREAM is change log, looking for a solution if the join results can be deferred so KAFKA TOPIC will receive summarized output.

You can't. The topic can only store the changelog. -- It's not possible to only store the **snapshot** because Kafka topics are immutable append-only logs: assume you would read both input topic from beginning to end, compute a "snapshot result" and finally write the "snapshot result" into the output topic. The query would still run because in a streaming system queries are continuous, and if upstream input data changes, the result would change, but the "snapshot result" was already written into the topic and cannot be changes any more. Does this make sense?

I am also not sure why you would need to only get the "summarized output" because there won't be a "final summarize output" anyway. In a streaming world, the is no final result and thus the result will change continuously when new input data arrives.

**Comment by mjsax** [comment]
Closing this question due to inactivity. Feel free to re-open if required.
