### ISSUE TITLE
Stream-table join value from table null when create new persistent stream

### ISSUE THREAD

**Issue by Bohatman** [confluentinc/ksql#7566]
Component:
1. ksql stream UPSTREAM_STREAM from topic: upstream
2. ksql table MASTER_TABLE from topic table

Create stream statement
`create stream persistent_stream  WITH(KAFKA_TOPIC='DOWNSTREAM',VALUE_FORMAT='JSON')
as select 
input.key,
input.field,
master.key,
master.field 
from UPSTREAM_STREAM input 
left join MASTER_TABLE  master on input.key = master.key`
As i know when create new stream it will have new consumer group prefix '_confluent-ksql-default_query_CSAS' it will poll message from source stream's topic and table's topic in case of table it will store data from table's topic to change-log topic

if table's topic have a lot of message such as 10M message
and new message coming before consumer group prefix '_confluent-ksql-default_query_CSAS' is 0 

message in topic 'DOWNSTREAM' field from table could be null

Can we pause consuming message before message lag from table's topic is 0?

**Comment by mjsax** [comment]
Stream-Table joins are temporal joins, and thus, updating the table and processing stream side records interleaves based on the record timestamps (to ensure that the correct "version" of the table is loaded when doing the lookup into the table). It does semantically not make sense to "bootstrap the table", because it would violate temporal semantics: your table could be semantically "in the future" (if it would be "bootstrapped") compare to when the stream side event happened. Remember that ksqlDB uses event-time semantics to avoid non-deterministic processing time.

Check out https://www.kafka-summit.org/sessions/temporal-joins-in-kafka-streams-and-ksqldb that explains it in more details. (Currently, this talk can be found in the Kafka Summit on-demand library -- you can just sign up for free for Kafka Summit to access it -- later, it will be migrated off the on-demand library into Confluents web page).

Thus, if you have table data that should be "loaded" upfront, the record in the table topic must have smaller timestamps than the records in the stream-side input.

**Comment by mjsax** [comment]
Closing this question due to inactivity. Feel free to re-open if required.
