### ISSUE TITLE
Why is there no mention of EMIT FINAL in the docs ?

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#8083]
You can use EMIT FINAL instead of EMIT CHANGES if you set "ksql.suppress.enabled" property to true, but there's no mention of it in the documentation. Is this deliberate and the feature will be removed in the future versions of ksqldb ? If not, you should probably include it into the docs.

**Comment by agavra** [comment]
Hi @maksymilian-gasztych - yes the omission is deliberate. There are some memory considerations with the feature that could cause unbounded growth and eventual an OOM execption. The feature is still in development/beta and we'll definitely document it when it's complete! 

Feel free to use it at your own risk in the meantime 😉 I'll close this ticket for now, since this is on our roadmap.
