### ISSUE TITLE
Investigate duplicated topic / store names

### ISSUE THREAD

**Issue by guozhangwang** [confluentinc/ksql#8154]
**Describe the bug**
This is from a feedback from Nick on slack: https://confluent.slack.com/archives/C337JP2F8/p1631659194201500?thread_ts=1631658714.201000&cid=C337JP2F8

I took a look at the source code, and saw that the names constructing the store names (and hence the changelog names) are stacked on `QueryContext` with the ops name, but it seems that sometimes we dup-stacking the names from the compiled physical plan.

It's worth investigating what's the root cause of the dup-stacking of the store names, whether it's easy to fix.

**Comment by vcrfxia** [comment]
Hi @guozhangwang , as discussed offline, it is intentional that some query contexts have "duplicate" names right now. The reason this happens is because query contexts start with names corresponding to logical plan nodes, then additional context pieces corresponding to physical steps are appended to the context for the logical plan node. Sometimes physical contexts have the same name as logical nodes, resulting in what appears to be duplication.

For example, here's a logical aggregation node with query context `Aggregate`:
https://github.com/confluentinc/ksql/blob/7f1d40775b317fa3f2a6df6bc3cb00fa13de86e1/ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java#L376
https://github.com/confluentinc/ksql/blob/7f1d40775b317fa3f2a6df6bc3cb00fa13de86e1/ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java#L150

Physical sub-steps for this logical aggregate node include `Prepare`, `Aggregate`, `GroupBy`, `HavingFilter`, and `Project`: https://github.com/confluentinc/ksql/blob/7f1d40775b317fa3f2a6df6bc3cb00fa13de86e1/ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java#L66-L70

Thus, you might see `Aggregate-Aggregate` as part of a query context.

I'm going to close this ticket as the report is not for a bug. Thanks.
