### ISSUE TITLE
KSQL join problem

### ISSUE THREAD

**Issue by chakhalyan1** [confluentinc/ksql#8270]
**Search for existing answers**
Many questions have been asked before.  Please have a quick search to see if there is already an answer to your question.  There are two main resources for finding answers:

1. [Existing KSQL Github issues, including closed_ issues](https://github.com/confluentinc/ksql/issues?utf8=%E2%9C%93&q=is%3Aissue+)
1. [KSQL on Stack Overflow](https://stackoverflow.com/questions/tagged/ksql)

If you can't see an answer to your question, then please raise a new Github or Stack overflow issue.

**Provide details of the setup you're running**
Let us know what version of KSQL you're running, what OS, etc, 
Version: 6.2.1,
OS: Ubuntu 18.04.5 LTS
Have run via docker-compose 
**Outline your question**

We are using KSQL streams and tables, before asking questions we have tested all typo of joins(stream-stream, stream-tables, table-table, etc...). If we not using from beginner join working ok, but if we do a query to stream or a table from the beginning then we have to get all event stories, not the latest table status. So if our service listens to the status events( joined table, or streams, etc..) and if we want to get only that events witch not produced( status not changed) we can not do that because we have received all event history which has the same key.

Example.

Create stream1 
`CREATE STREAM stream_1 (id VARCHAR KEY, user_id VARCHAR)
WITH ( KAFKA_TOPIC = 'topic_1', KEY_FORMAT='KAFKA', VALUE_FORMAT = 'AVRO', PARTITIONS=1, REPLICAS=1);`
Create stream2
 `CREATE STREAM stream_2 (id VARCHAR KEY, status INT) 
WITH ( KAFKA_TOPIC = 'topic_2', KEY_FORMAT='KAFKA', VALUE_FORMAT = 'AVRO', PARTITIONS=1, REPLICAS=1);`
Insert to stream1
`INSERT INTO stream_1 (id, user_id)
VALUES ('10000', '001');`
Insert to stream2
INSERT INTO stream_2 (id, status)
VALUES ('10000', 1);

Then do the following wing join query from the beginning
`SELECT * 
FROM  STREAM_1 s1
LEFT JOIN  STREAM_2 s2 WITHIN 1 HOUR on s1.id = s2.id
EMIT CHANGES;`

result is 
`{"S1_TX_ID":"10000","S1_USER_ID":"001","S2_TX_ID":"10000","S2_STATUS":1 {"S1_TX_ID":"10000","S1_USER_ID":"001","S2_TX_ID":null,"S2_STATUS":null}`
The same  query on SQL language was returned only  first row.

**Comment by mjsax** [comment]
It's a know problem and related to Kafka Streams: https://issues.apache.org/jira/browse/KAFKA-10847

Closing as duplicate to https://github.com/confluentinc/ksql/issues/1558

It's fixed in upcoming 0.23 release.

**Comment by chakhalyan1** [comment]
thank You for answering, of course, it will be very useful when event streaming architecture has more processes and after the same stapes one service was crashed, after recovery, service can continue  from that event

**Comment by mjsax** [comment]
Not sure if I fully understand your last sentence?

> after the same stapes one service was crashed, after recovery, service can continue from that event

This is how (persistent) queries works today. If a (persistent) query crashes and ksqlDB recovers from the crash (eg, server restart, or the query get migrated to a different server), query state would be re-build and the query would resume where it left oft before the crash.

Or are you talking about a crashing client? This is more challenging and there is no built in fault-tolerance for transient push queries. The currently recommended pattern is, to use persistent queries that write the result into a Kafka topic, and let the client read from the Kafka topic (instead of using push queries). This way, queries become fault tolerant, and Kafka's consumer group protocol allows clients to resume reading the result where they left off before the crash.
