### ISSUE TITLE
Document restrictions on record key when key column is declared

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#847]
We use the String serde to serialize/deserialize record keys. If the value in the key is in a binary format, this can cause different keys to deserialize to the same String value. This can cause collisions for stateful operations (aggregations, joins). Normally this doesn't happen because we first repartition, and the repartition uses a key generated by converting the values in the relevant columns to Strings. The exception is the case where we optimize for aggregations/joins by skipping repartitions if the stream is keyed on the column in GROUP BY. We should not make this optimization if the key column is not a STRING/VARCHAR.

**Comment by apurvam** [comment]
It is worth noting that the optimized group by has a problem because we directly interpret the bytes as a string and deserialize it as such. In particular we create the string from the bytes with `new String(bytes, "UTF-8")`.

This leads to problems as demonstrated below. The asserts pass. Meaning that two different integers get interpreted as the same string, and that string serializes to the same bytes.

```java
public void testStringSerde() {    
    ByteBuffer buf = ByteBuffer.allocate(4);
    buf.putInt(0x00000080);
    String s1 = new String(buf.array(), "UTF-8");

    buf.clear();
    ByteBuffer buf2 = ByteBuffer.allocate(4);
    buf2.putInt(0x00000081);
    String s2 = new String(buf2.array(), "UTF-8");

    byte[] bytes1 = s1.getBytes("UTF-8");
    byte[] bytes2 = s2.getBytes("UTF-8");
    Assert.assertEquals(s1, s2);
    Assert.assertArrayEquals(bytes1, bytes2);
}
```

It is not a problem in cases like in `PARTITION BY` because we do a `column.toString()`. In the non-optimized `GROUP BY` we do `String.valueOf(column)`, which achieves the same result: we don't directly interpret the column as a string, but convert the column value to a string.

But the that raises the question about things like 'filter'. If the underlying topic has a non int key we can still potentially have key collisions right? It seems to me that we don't ever explicitly convert the key to a string, but just interpret the bytes as a string, leading to the same problem as the non-optimized `GROUP BY`. If it's a stream, the filter would cause an implicit repartition. But for tables, it would cause clobbering. Is this true? Are there other operations with similar problems? Is it worth doing an audit?

**Comment by rodesai** [comment]
> If it's a stream, the filter would cause an implicit repartition. But for tables, it would cause clobbering.
This is a good point. I think is also a problem. I've been working on some test cases that reproduce this issue for aggregations and joins. I'll add something for project/filters on tables.

> Are there other operations with similar problems? Is it worth doing an audit?
In general I think this is a potential issue whenever a query requires a state store. I can't think of any other instances KSQL would create a topology with a state store other than aggregations, joins, or CTAS where the src is a table. Still, I think it's worth going through the topology building stuff and auditing usages of the record key.

**Comment by apurvam** [comment]
I think generally reading non-string values as UTF-8 strings is dangerous. Even if you don't actually corrupt data by clobbering, you will still repartition data non-randomly, possibly creating skews. 

IMO, in the absolutely short term we should do an audit to make sure we don't clobber data because of this. In the near term we should just stop interpreting keys as strings, but treat them as opaque bytes instead.

**Comment by rodesai** [comment]
For the very short term we've decided to document the restriction that the record key must be a utf-8 string representation of the declared key column, along with how to repartition your topic using ksql if it is not. In the near term we will switch to a binary serde for the key.

**Comment by miguno** [comment]
This larger issue is related to https://github.com/confluentinc/ksql/issues/724

**Comment by miguno** [comment]
Also related to https://github.com/confluentinc/ksql/issues/824.
