### ISSUE TITLE
KSQL can't match >1 wildcard in LIKE statement

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#867]
Given this data: 

```
ksql> select facility, level, message from UBNT_SYSLOG
3 | 6 | ("U7PG2,f09fc2238301,v3.7.40.6115") hostapd: ath0: STA cc:2d:b7:bf:3c:07 IEEE 802.11: associated
```

The following statement should match, but returns nothing: 

```
select facility, level, message from UBNT_SYSLOG where facility=3 AND MESSAGE LIKE '%cc:2d:b7:bf:3c:07%associated%';
```

Splitting the `LIKE` into two clauses works: 

```
select facility, level, message from UBNT_SYSLOG where facility=3 AND MESSAGE LIKE '%cc:2d:b7:bf:3c:07%' AND MESSAGE LIKE '%associated%';
```

**Comment by big-andy-coates** [comment]
Looking at the code, `LIKE` only currently supports the wildcard `%` character at either the beginning of the search term, or the end, or both.  If does not support `%` in the middle.

Code comments suggest this is intentional:
https://github.com/confluentinc/ksql/blob/765cb43f1a8d81f5343abe035e0eda1d8ccdd0a7/ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java#L505

So this would be an enhancement, plus a bug in the docs.

**Comment by rmoff** [comment]
Closing to track in #2054 which covers a broader use
