### ISSUE TITLE
Add support for INSTR function

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#881]
It would be useful to add support for a `INSTR` function (same in concept to [this](https://docs.oracle.com/database/121/SQLRF/functions089.htm#SQLRF00651)). 

Combined with `SUBSTR` it enables data munging of a given string field.

**Comment by rmoff** [comment]
Similar to support for CASE (#620), supporting `INSTR` opens up a lot more potential for KSQL in the data wrangling/ETL space.

**Comment by rmoff** [comment]
`indexOf` is the same function that people might want, adding it here to make it easier to search for.

**Comment by sakshiganeriwal** [comment]
Hey @apurvam, I am new to open sourcing and was looking for projects to contribute to. I have used Kstreams and read an article on KSql and found it very interesting. I wanted to start off with something to understand the codebase so that i could contribute. And i saw this marked as a `good first issue`. I saw the PR for CASE and was trying to see what `INSTR` was implemented  but i am a little confused on where can i look for implementing this. Can you guide me on this?

**Comment by mateuszmrozewski** [comment]
@rmoff, this is merged to master now.

**Comment by rmoff** [comment]
Awesome, thank you @mateuszmrozewski
