### ISSUE TITLE
Emit final dont flush by window close.

### ISSUE THREAD

**Issue by devopg** [confluentinc/ksql#9007]
hi i have table with windows thumbling 60 second but after windows close (after 60 second)  ,  calculated value dont flush.

Reproduce: 

```
CREATE STREAM MOVIE_TICKET_SALESF (title VARCHAR, c INT)
    WITH (KAFKA_TOPIC='movie-ticket-salesf',
          PARTITIONS=1,
          VALUE_FORMAT='json');
```

` create table table_thumb60secf as select title, count(*) from  MOVIE_TICKET_SALESF window tumbling (size 60 second) group by title emit final;
`

Insert and wait 60 second 
```
 insert into MOVIE_TICKET_SALESF values ('a', 1);
 insert into MOVIE_TICKET_SALESF values ('a', 1);
 insert into MOVIE_TICKET_SALESF values ('a', 1);
 insert into MOVIE_TICKET_SALESF values ('a', 1);

```

And watch: 
` select * from  TABLE_THUMB60SECF  emit changes;`

and 
` print TABLE_THUMB60SECF;`

After waiting 60 seconds , we won 't see anything
To see the last result from the previous window, you need to turn it again!
` insert into MOVIE_TICKET_SALESF values ('a', 1);`

![image](https://user-images.githubusercontent.com/61819835/162751057-c1604b9b-be9f-484a-9c80-f2160f9f4d92.png)

**Comment by nateab** [comment]
This is actually due to the difference between _stream time_ and _wall clock time_. Stream time is just the latest timestamp that we have received so far, and this is what we use for time kafka streams and ksqldb. 

Here are some relevant links you may be interested to learn more about the differences:
https://www.confluent.io/blog/kafka-streams-take-on-watermarks-and-triggers/
https://cwiki.apache.org/confluence/display/KAFKA/KIP-424%3A+Allow+suppression+of+intermediate+events+based+on+wall+clock+time

**Comment by nateab** [comment]
What exactly do you need? For the example you described above, yes you need to add another event outside of the window in order to advance stream time and flush the result. But if you are using this as part of some real use case that has streaming data, the queries you shared should be fine since the continuously streaming data will advance streamtime.

Grace period is meant to help with late out of order events, but if you dont't need it you could set it to 0 I think 
See https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#out-of-order-events
