### ISSUE TITLE
INSERT/VALUES fails when SR key schema differs from the schema resolved by KSQL

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#9438]
**Describe the bug**
This issue happens when I create a stream or table that infers its schema from an existing SR key schema I registered before. This SR key schema has properties that CREATE won't add if I leave CREATE to register the schema. For instance, the below schema has `doc` properties to help me add comments in the schema. It also uses a different name and namespace:
```
{
  "doc": "Sample schema to help you get started.",
  "fields": [
    {
      "doc": "The int type is a 32-bit signed integer.",
      "name": "C1",
      "type": "int"
    }
  ],
  "name": "sampleRecord",
  "namespace": "com.mycorp.mynamespace",
  "type": "record"
}
```

I can create a schema using the above SR schema:
```
ksql> create stream test(id int) with (kafka_topic='test', key_format='avro', key_schema_id=1);

 Message        
----------------
 Stream created 
----------------

ksql> describe test;

Name                 : TEST
 Field  | Type                     
-----------------------------------
 ROWKEY | STRUCT<C1 INTEGER> (key) 
 ID     | INTEGER                  
-----------------------------------
```

But when I run INSERT, then it fails with this:
```
ksql> insert into test(rowkey, id) values(struct(c1:=1), 1);
Failed to insert values into 'TEST'. Cannot INSERT VALUES into data source `TEST`. ksqlDB generated schema would overwrite existing key schema.
	Existing Schema: {"type":"record","name":"sampleRecord","namespace":"com.mycorp.mynamespace","doc":"Sample schema to help you get started.","fields":[{"name":"C1","type":"int","doc":"The int type is a 32-bit signed integer."}]}
	ksqlDB Generated: {"type":"record","name":"sampleRecord","namespace":"com.mycorp.mynamespace","fields":[{"name":"C1","type":["null","int"],"default":null}],"connect.name":"com.mycorp.mynamespace.sampleRecord"}
```

The issue is that the INSERT/VALUES is comparing the SR key schema with the schema resolved by KSQL and then compares the raw string. Both schemas should be the same (same field names, field types and column orders), but the strings are different.

I think we can fix this by resolving the SR schema into a KSQL column schema. For instance, both schemas above (SR and KSQL resolved schema) are `ROWKEY STRUCT<C1 INTEGER>, ID INTEGER`. Both schemas are equal if resolved that way, then why letting fail because the strings are different?

**Comment by colinhicks** [comment]
Thanks for the description and potential solution above. I had a couple questions to check my understanding. /cc @spena @bvarghese1 @lihaosky @pgaref @aliehsaeedii 

> The issue is that the INSERT/VALUES is comparing the SR key schema with the schema resolved by KSQL and then compares the raw string. Both schemas should be the same (same field names, field types and column orders), but the strings are different.

Do we understand why a string comparison is currently used, rather than delegating the compatibility check to schema registry? It seems like SR would be able to correctly compare schemas in the case where the schemas are equivalent except for extras like `doc` props in Avro.

On the other hand, an SR-based check wouldn't work if the existing schema uses a different Avro name/space, even if the fields are otherwise equivalent. Comparing instead with the KSQL column schemas would solve for this case, since any namespacing is factored out, right?

One other thing I'm still not clear on: If the stream was created using an explicit schema ID for key and/or value, why don't we use that explicit schema when executing the insert statement, rather than having KSQL generate a new one? Is it to handle cases when the explicit schema does not specify nullable fields, but an insert statement does not specify all non-nullable columns?

**Comment by bvarghese1** [comment]
"On the other hand, an SR-based check wouldn't work if the existing schema uses a different Avro name/space, even if the fields are otherwise equivalent. Comparing instead with the KSQL column schemas would solve for this case, since any namespacing is factored out, right?"
@colinhicks Yes, we are doing what you described here in this PR - https://github.com/confluentinc/ksql/pull/9412

**Comment by spena** [comment]
> Do we understand why a string comparison is currently used, rather than delegating the compatibility check to schema registry? It seems like SR would be able to correctly compare schemas in the case where the schemas are equivalent except for extras like doc props in Avro.

The `ensureKeySchemasMatch` was added because INSERT/VALUES was overriding the SR schema with a new one. It's part of this PR https://github.com/confluentinc/ksql/pull/6601/files. Looking at the PR, I think it was just a quick fix to prevent overriding the schema. There was not deeper investigation of the SR API, just that it might override, so string comparison was a quick fix. We could use the SR API comparison but the `auto.register.schemas` and `id.compatibility.strict` weren't understood yet. Now, we can disable them, but we do it only when the KEY_SCHEMA_ID is specified, which the fix on https://github.com/confluentinc/ksql/pull/9412 does. If no schema_id is used, then it uses the latest schema id.

> On the other hand, an SR-based check wouldn't work if the existing schema uses a different Avro name/space, even if the fields are otherwise equivalent. Comparing instead with the KSQL column schemas would solve for this case, since any namespacing is factored out, right?

It's right. Although I'm not sure if the `id.compatibility.strict` will solve the issue of the namespaces and docs comparison. Anyway, we need the schema ID in order to use `id.compatibility.strict`, otherwise it it will check names too.

> One other thing I'm still not clear on: If the stream was created using an explicit schema ID for key and/or value, why don't we use that explicit schema when executing the insert statement, rather than having KSQL generate a new one? Is it to handle cases when the explicit schema does not specify nullable fields, but an insert statement does not specify all non-nullable columns?

I don't know either. @lihaosky may know more about this. The KEY_SCHEMA_ID was added after the `ensureKeySchemaMatch`. I'm more inclined to the idea that if we currently support adding more fields on CREATE OR REPLACE without updating the schema on SR, or specifying a subset of the KEY_SCHEMA_ID, then we should not allow INSERT with a KSQL key different than SR keys. That would cause the repartition issue if other producers (outside KSQL) use the SR key schema for that. So we should check the latest schema ID just to be safe? We should investigate more about these cases, though.
