### ISSUE TITLE
Support for configuration that allows to prevent skipping of records when deserializaion of a field fails.

### ISSUE THREAD

**Issue by NitronR** [confluentinc/ksql#9521]
**Is your feature request related to a problem? Please describe.**
Currently, when deserialization fails for a field due to issues such as unable to coerce an input value to a field's data type, the corresponding record is skipped. For example: if we have an integer field 'amount' then record will be skipped if a string value is passed for that field.

**Describe the solution you'd like**
Our use case have few fields which are not important and these should not cause the record to be skipped if some invalid input starts coming in from the source system. This will allow the downstream queries that operate on other fields to process this record. The deseralization error can be logged for debugging purpose with suitable metrics if required.

**Describe alternatives you've considered**
Alternative suggested on slack: Use array of bytes as data type so deserialisation failures do not occur. For getting the value, write a UDF for converting the array of bytes to required data type.
This seems like a workaround that will be difficult to maintain.

**Comment by agavra** [comment]
You can set `ksql.fail.on.deserialization.error` to achieve this behavior :) Let me know if that solves your use case.

**Comment by vcrfxia** [comment]
If I'm understanding the question correctly, it sounds like the request is for invalid records to not be skipped, but instead to be forwarded downstream. Unfortunately that doesn't fit well with SQL being a strongly typed system. Taking the example from above, if there is an integer-value column and a particular record contains a string instead, how should the string be interpreted in expressions involving the column that expect an integer? For columns which are meant to be truly untyped, a generic BYTES type (per the suggested workaround) allows a way to pass-through arbitrary data from source to sink. But it sounds like you also want the column to be typed? I'm not sure how both of those can be possible at the same time. Perhaps some example queries and expected behavior on different types of rows would help.
