### ISSUE TITLE
create or replace fails on recent versions due to new valueFormat field.

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#9755]
**Describe the bug**
create or replace fails on recent versions due to new valueFormat field that was added in 0.24.0

**To Reproduce**
- Start up 7.0.1 server connected to SR
- Create the following stream `create protoTest (test BIGINT) with(kafka_topic='protoTest102', value_format='protobuf', partitions=1);
- Upgrade to 0.28.0
- Run the following create or replace statement `create or replace stream protoTest with(kafka_topic='protoTest102', value_format='protobuf', partitions=1);`

**Expected behavior**
create or replace works

**Actual behaviour**
Fails with 
```
Cannot upgrade data source: DataSource '`PROTOTEST`' has topic = KsqlTopic{kafkaTopicName='protoTest102', keyFormat=KeyFormat{format=FormatInfo{format=KAFKA, properties={}}, features=[], window=Optional.empty}, valueFormat=ValueFormat{format=FormatInfo{format=PROTOBUF, properties={}}, features=[]}} which is not upgradeable to KsqlTopic{kafkaTopicName='protoTest102', keyFormat=KeyFormat{format=FormatInfo{format=KAFKA, properties={}}, features=[], window=Optional.empty}, valueFormat=ValueFormat{format=FormatInfo{format=PROTOBUF, properties={unwrapPrimitives=true}}, features=[]}}
```

**Additional context**
When comparing the KsqlTopics between the old and new stream definition, the properties field of ValueFormat include the properties field, so since it's different between the two, it's not considered compatible and the statement fails.

The only workaround is to modify the problematic statement in the command topic manually by recreating it and then restarting the server.

**Comment by vcrfxia** [comment]
Hey @stevenpyzhang tl;dr this behavior is intentional, and that workaround is fine. We have options for modifying the code to make the workaround less manual/invasive but even if we do that, users will still need to take extra steps in order to specify that this upgrade is OK with them.

The long version for why this behavior is intentional: if the `unwrapPrimitives` property (protobuf-only format property) does not match between query versions, then that can result in a backwards-incompatible change. The property was introduced on a version between 7.0.1 and 0.28.0, which is why the query issued on 7.0.1 doesn't have it explicitly set but on 0.28.0 there now is a value set. ksql has no easy way of determining what the default value on older versions is/was, because it's inconsistent: for example, 7.0.1 has default "false" while 7.1.0 has default "true". (There was a breaking change that unintentionally slipped in from a dependency, which is what prompted us to introduce `unwrapPrimitives` in order to clean up the issue.) As a result, the safer thing to do is to not guess a default and mark the upgrade as incompatible out of caution.

If a user is confident that the change in this property does not impact their query (e.g., because they do not use protobuf wrapped primitives in their query), then the workaround you provided of modifying the command topic is totally fine. Perhaps a cleaner way for users to do this could be to expose the `unwrapPrimitives` property as a WITH clause property in the query, but we didn't do that at the time since we weren't expecting many use cases for it. If this CREATE OR REPLACE issue continues to be a problem for users, then that could be enough of a reason to add the WITH clause property. Even if we do that, then users will still need to modify their query statement to add the WITH clause property to get the CREATE OR REPLACE to work, and that's very much intentional.
