### ISSUE TITLE
ksqlDB migrations tool HTTP2 Error when trying to apply migrations via ksqldb-cli docker image

### ISSUE THREAD

**Issue by farhan-triplelift** [confluentinc/ksql#9811]
I am trying to use [ksqlDB migrations tool](https://docs.ksqldb.io/en/latest/operate-and-deploy/migrations-tool/):   via a Github Actions file like so: https://github.com/jzaralim/ksqldb-migrations-action/blob/main/.github/actions/ksqldb-migrations-apply/action.yaml. When running my migrations I receive this error:

```
io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: This endpoint is only available when using HTTP2. Error code: 40004.   
```

 Running the latest version of both the CLI and ksqlDB Server (0.28.2)

**To Reproduce**
ksqldb-cli: 0.28.2
ksqldb-server: 0.28.2

1. Setup migration-tool in Github repository like so: https://docs.ksqldb.io/en/latest/operate-and-deploy/migrations-tool/#initial-setup
2. Initialize migrations tool via ksqldb-cli 
3. Run ksqldb migrations apply Github action like so : https://github.com/jzaralim/ksqldb-migrations-action/blob/main/.github/actions/ksqldb-migrations-apply/action.yaml. except version is 0.28.2

**Expected behavior**
Migrations should apply successfully via Github action runner on ksqldb server via docker ksqldb cli image 

**Actual behaviour**
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating current migration state before applying new migrations
Loading migration files
2 migration file(s) loaded.
Applying migration version 1: create-mysql-connector
/github/workspace/migrations/V000001__create-mysql-connector.sql contents:
<REDACTED SQL QUERY>
io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: This endpoint is only available when using HTTP2. Error code: 40004
Execution time: 2.6100 seconds
```

**Additional context**
It seems that both the initialize migration tool endpoint and validate migrations actions work just fine via the docker ksqldb cli image. It is only when running the apply migrations does it fail.

It seems that the crux of the issue is that the apply action that is run via the migrations tool in the ksqlDB CLI image is not sending requesting via http2 while the ksqldb server is expecting it to be http2

**Comment by farhan-triplelift** [comment]
```
[2023-03-01 21:24:48,807] ERROR Failed to handle request 400 /inserts-stream (io.confluent.ksql.api.server.FailureHandler:41)
```

```
[2023-03-01 21:24:48,716] INFO 10.204.50.253 - - [Wed, 1 Mar 2023 21:24:48 GMT] “POST /ksql HTTP/1.1” 200 2971 “-” “ksqlDB Java Client v0.28.2” 68 (io.confluent.ksql.api.server.LoggingHandler:144)
```
It looks like the migrations tool is sending requests to the /insert-stream endpoint(ksqldb-server) under the hood which is expecting an HTTP2 Request. The ksqlDB Java client v0.28.2 is sending it via HTTP/1.1 for whatever reason

**Comment by farhan-triplelift** [comment]
It seems that this endpoint is the only endpoint that requires HTTP2 for some reason: https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/test/java/io/confluent/ksql/api/Http2OnlyStreamTest.java

**Comment by farhan-triplelift** [comment]
Though it seems that the ksqlClient that the ksqldb-tools project uses does have the client set to HTTP2 here: https://github.com/confluentinc/ksql/blob/master/ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java#L900. Not sure why its sending requests with HTTP1.1

**Comment by farhan-triplelift** [comment]
cc: @jzaralim @aliehsaeedii

**Comment by vcrfxia** [comment]
Hey @farhan-triplelift can you share the contents of the migration you tried to apply when you hit that error? Feel free to redact the data itself but I'd like to see the structure of the statements. I assume you have some `INSERT VALUES` statements in there, since your migration is trying to reach the `/inserts-stream` endpoint. I tried to reproduce the issue with a migration file containing a `CREATE STREAM` and an `INSERT VALUES` statement just now and did not encounter the error, which makes me wonder if it's something specific to either your migrations statements or your setup.

As you've noted above, the migrations tool uses the ksqlDB Java client which sends all requests with HTTP/2, so the error message you've encountered is very odd. What's the setup between your client and your ksqlDB server? Wondering if there could be intermediate networking layers at play.

**Comment by farhan-triplelift** [comment]
Hi @vcrfxia sure these are the contents of the migrations file:

```
CREATE SOURCE CONNECTOR deal_change WITH (
    'connector.class'          = 'io.confluent.connect.jdbc.JdbcSourceConnector',
    'connection.url'           = 'jdbc:mysql://redacted',
    'connection.user'          =  'redacted',
    'connection.password'      =  'redacted',
    'topic.prefix'             = 'jdbc_redacted',
    'mode'                     = 'timestamp+incrementing',
    'numeric.mapping'          = 'best_fit',
    'incrementing.column.name' = 'id',
    'timestamp.column.name'    = 'last_modified',
    'key'                      = 'id',
    'key.converter'            = 'org.apache.kafka.connect.converters.LongConverter',
    'query'                    = 'redacted'
);

```
I actually don't have any insert statements in this statement query.

So the setup we currently have is that our ksqlDB server is deployed onto an EC2 instance via nomad. We're leveraging the latest dockerhub image - confluentinc/ksqldb-server: 0.28.2.

**Comment by vcrfxia** [comment]
> I actually don't have any insert statements in this statement query.

I see. In that case the issue should not be related to the contents of your migration, since the `/inserts-stream` endpoint is only hit after the ksql-migrations tool has applied (or at least tried to) your migration, in order to update the status of the migration in the migrations table. 

Given that I am unable to reproduce the issue, it's likely environmental. What happens if you try to hit the `/inserts-stream` endpoint of your ksqlDB server yourself, from where your client is running? Also, do your server logs confirm that the attempt to reach the `/inserts-stream` endpoint was using HTTP/1.1?

**Comment by farhan-triplelift** [comment]
Yes I just tried running the GitHub action and this is my cloudwatch server log where my ksqldb-server is running:

`[2023-03-09 02:12:52,584] WARN 10.204.77.208 - - [Thu, 9 Mar 2023 02:12:52 GMT] "POST /inserts-stream HTTP/1.1" 400 105 "-" "ksqlDB Java Client v0.28.2" 0 (io.confluent.ksql.api.server.LoggingHandler:142)`

**Comment by farhan-triplelift** [comment]
I don't receive that HTTP2 error when running these statements/queries directly while running the CLI on my machine or if I use POSTMAN to hit the ksqldb server's "/ksql" endpoint

**Comment by farhan-triplelift** [comment]
Looks like when I hit the `/insert-stream` endpoint directly from POSTMAN, this is what shows up in my cloud watch logs:

`[2023-03-09 02:39:02,326] WARN 10.204.50.253 - - [Thu, 9 Mar 2023 02:39:02 GMT] "POST /insert-stream HTTP/1.1" 404 53 "-" "PostmanRuntime/7.29.2" 0 (io.confluent.ksql.api.server.LoggingHandler:142)`

**Comment by farhan-triplelift** [comment]
When I try to hit the /inserts-streams directly from POSTMAN I actually get a 400 error with this as the response:

`{"@type":"generic_error","error_code":40004,"message":"This endpoint is only available when using HTTP2"}`

**Comment by farhan-triplelift** [comment]
So after using the above curl query you posted (with my ksqldb server's url) I still get this:

`{"@type":"generic_error","error_code":40004,"message":"This endpoint is only available when using HTTP2"}`

This leads me to belive its an issue with a configuration on my ksqldb server client. 

I checked and it seems that POSTMAN does still not yet support HTTP2

**Comment by vcrfxia** [comment]
Given that your ksqlDB server logs show the request coming in as using HTTP/2, it makes me suspect something wrong with the networking. Are you able to access where your ksqlDB server is running, and issue the request from there? It would be good to try to isolate whether the issue is with the server itself or with the networking between your client and server.

**Comment by farhan-triplelift** [comment]
So I've executed this request to `/inserts-stream` via my local machine cURL (making sure the request explicitly was sending the request through HTTP2). This resulted in the same cloud watch log saying that the request was sent as HTTP/1.1. I've also leveraged the ksqlDB CLI docker image to send the request via a GitHub Instance runner which is a different client from my local machine.  

And yes I am able to issue a request from the box where my ksqldb server is hosted and I get the same result. So at this point, that's 3 different clients serving the same request that result in this HTTP/2 error from the `/inserts-stream` endpoint. Should I maybe try downgrading my ksqldb server version?

**Comment by vcrfxia** [comment]
> I am able to issue a request from the box where my ksqldb server is hosted and I get the same result

When you did this, did you use the same public server address that you used previously, or did you update the server address to `localhost` (or equivalent)? The latter is the relevant test. If that also converted your HTTP/2 request into an HTTP/1.1 request, then that's very weird.

> Should I maybe try downgrading my ksqldb server version?

I am able to run ksqlDB server 0.28.2 and ksqlDB CLI 0.28.2 on my local machine and successfully issue HTTP/2 requests, so I don't think it's the server version, but if you didn't have this issue on an older server version in the past then it could be worth a try. 

> could it be potentially also a configuration on the ec2 instance that is hosting the ksqlDB server not allowing HTTP2 requests?

Yes, this is the type of issue I am suspecting, though I don't know whether it would be specifically the EC2 configuration or something else. If it's not too difficult to set up another ksqlDB server for test purposes on a different machine (e.g., your local machine, instead of on an EC2 instance), you could try that to see if you encounter the same issue.

**Comment by vcrfxia** [comment]
As of a few years ago, it looks like AWS users were encountering issues with HTTP/2 requests being downgraded to HTTP/1.1 unexpectedly: https://github.com/aws/aws-sdk-go/issues/2984 AFAICT that specific issue should be fixed as of late 2020 since AWS [released](https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/) HTTP/2 support for load balancers but this is exactly the sort of thing which could be happening in your networking setup. It'd be good to check the various components you're using in case any do not support HTTP/2.

**Comment by farhan-triplelift** [comment]
After further investigation, it looks like this was a configuration issue on our EC2 instance target group to enable HTTP2. Closing out this issue.

**Comment by ievgenii-shepeliuk** [comment]
> After further investigation, it looks like this was a configuration issue on our EC2 instance target group to enable HTTP2. Closing out this issue.

Hello @farhan-triplelift 
I have the same issue, but in access logs of my API GW (Traefik)  I am seeing that request are sent with HTTP/2.

How did you exactly solve the issue ? Can you describe plz ?
