### ISSUE TITLE
Can I create 2 streams (CREATE STREAM AS SELECT) that write to the same topic?

### ISSUE THREAD

**Issue by ws2003gq** [confluentinc/ksql#983]
I have 2 original source topic with different data and create 2 streams for them.
Then I want to create 2 queries to analyze them and sink to the same topic.
But I got the failed notice below:
```
ksql> CREATE STREAM st_qr_lori_r_playvideorecord WITH (kafka_topic='r_playvideorecord', value_format='JSON', PARTITIONS=50,REPLICAS=1) AS select cip as "cip",id as "id",hostname as "hostname",timestamp as "@timestamp",geoiplocation as "geoiplocation",geoipcityname as "geoipcityname",geoipprovincename as "geoipprovincename",rh['uid'] as "uid",rh['msisdn'] as "msisdn",rh['ua'] as "ua",rh['version'] as "version",rh['idfa'] as "idfa",rh['IMEI'] as "imei",params['contentId'] as "contentid",params['beginTime'] as "playstarttime",params['endTime'] as "playendtime",params['resourceType'] as "resourcetype",params['rateLevel'] as "ratelevel",params['parentId'] as "parentid" from stream_lori_log where stream_lori_log.id 

='old_download_video';
io.confluent.ksql.util.KsqlException: Cannot add the new topic. Another topic with the same name already exists: r_playvideorecord
```
Is that right? or how can I do?

**Comment by blueedgenick** [comment]
it's correct that you cannot yet do this, because the CREATE STREAM AS will try to (re-)create the output topic for you. One option that was discussed earlier (I think in the community slack channel, can't seem to find an open issue for it just now) is to add support for INSERT INTO <stream>, which would allow to write to an output topic from multiple queries.  If you think about it, the CREATE STREAM AS SELECT syntax is logically only a syntax shortcut for "create output topic" followed by "insert into output topic" anyway...

**Comment by ws2003gq** [comment]
Got it.thanks for your help and wish to use it (INSERT INTO) eariler.

**Comment by apurvam** [comment]
See https://github.com/confluentinc/ksql/pull/576
