### ISSUE TITLE
Slow Performance for Materialized View Pull Query over REST Request

### ISSUE THREAD

**Issue by Rap70r** [confluentinc/ksql#9838]
Hello,

I have a Kafka cluster that is ingesting data from SQL Server using Debezium connector. The current format is Avro. My Topics are quite large (millions of records) and partitioned. I followed below guide to setup KSqlDB over my existing Kafka Topics:

Tutorial: https://docs.ksqldb.io/en/latest/tutorials/materialized/

I created a Materialized cache on a large table that contains over 80 million records. After that, I tried to query the view over Rest API, however, the performance is very slow. It takes few minutes to return data when querying for a single key.
Can you please provide some insight on how to enhance and configure the setup and build Materialized cache around large topics that can be queried over a Rest API?

Thank you

**Comment by vcrfxia** [comment]
Hi @Rap70r , can you double-check that the table you have materialized has a single key column, and that the column you are using in the WHERE clause for your filter is in fact the key column? You can do this by using `DESCRIBE <TABLE>;` to view which column(s) are listed as key columns.

Also, how large is each of your 80 million records? If your query is performing a lookup on a single key, it's surprising that it takes minutes, unless the records themselves are very large, which makes me wonder whether perhaps the query is actually being executed as a table scan.

**Comment by Rap70r** [comment]
Hi @vcrfxia, Thank you for getting back to me. I spent some time going over my resources and reading the documentation. I was able to create a materialized view from a Stream that was based on the same topic that contains more than 80 million records. I was able to query individual records within a second. Which is great. However, since my SQL tables have a composite keys, I created my views using the following structure:
```
CREATE STREAM some_stream_name WITH (
    kafka_topic = 'some.topic.name',
	value_format = 'avro'
);
	
CREATE TABLE some_view_name AS
	SELECT
        CAST(after->key_column_one AS STRING) + '|' + CAST(after->key_column_two AS STRING) + '|' + CAST(after->key_column_three AS STRING) AS MyViews_PK,	
		
		*200 more columns here*
		
		count_distinct(after->some_column) AS distinct_keys
	FROM some_stream_name
	GROUP BY CAST(after->key_column_one AS STRING) + '|' + CAST(after->key_column_two AS STRING) + '|' + CAST(after->key_column_three AS STRING)
	EMIT CHANGES;
```
And this is the POST request's payload:

```
select * from some_view_name where MyViews_PK in (*100 composite keys here separated by comma*);
```

When I try to query the above, it takes couple of minutes to return. I was wondering, what are the techniques to performance tuning of this setup? I understand the view is stored using RocksDB. Are there any configs that can make the query faster or concurrent? 

Thank you

**Comment by Rap70r** [comment]
@vcrfxia, thank you for your detailed answer. Here are the details: The request for a single key lookup takes less than a second to return. The topics are derived from a SQL Server table that are 180 columns wide and consist of various column types such as varchars and decimals. Nothing out of ordinary. 
KSqlDB server is an AWS EC2 instance (i4i.2xlarge) with 8 CPUs and 64 GB of Ram. Both server and client are located on the same geographical region. I'm not sure how to tell how many standbys nodes enabled are there. Do you mind guiding me through this? A single record in a Json format returned by the pull query is 8KB in size.
Also, to give you some details about our use case in order to let me know if this is feasible with KSqlDB. We have a SQL Server that contains Table with data and each table's size is between 300K and 100 Million records. We are currently streaming these table into a Kafka cluster. What we are trying to test is if we could utilize KSqlDB RESTful architecture to retrieve data from 1 or multiple tables based on custom queries from clients over REST API requests. I'm very new to KSqlDB and I cannot determine if the bottleneck is simply hardware in order to scale up or if it's something else. I will definitely look into the resources you have shared. Any additional input regarding our setup and use case would be greatly appreciated.

Thank you

**Comment by vcrfxia** [comment]
> I'm not sure how to tell how many standbys nodes enabled are there.

If you only have one instance, then you have no standbys. If all your data fits on a single instance, then that will be faster than switching to a multi-node deployment and enabling standbys, given that your clients are all in the same region anyway, so I wouldn't worry about that.

> can you please share details on how to switch the compaction level of KSqlDB's RocksDB?

The built-in ksqlDB RocksDB config setter does not support this (yet -- there is ongoing work to add it). Unless you want to wait for that patch, you'll have to implement your own config setter. You can base it off the ksqlDB RocksDB config setter ([link](https://github.com/confluentinc/ksql/blob/master/ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigSetter.java)), just additionally set the compaction style. Compaction style is simply another RocksDB option ([link](https://javadoc.io/doc/org.rocksdb/rocksdbjni/latest/org/rocksdb/Options.html#setCompactionStyle-org.rocksdb.CompactionStyle-)), similar to the others already being set in the ksqlDB config setter.

> One thing I did notice is when I start the service, the CPU hits 100% and remains high. Could that be contributing to the bottleneck?

Yeah definitely. If that CPU spike is caused by your pull query workload, then that definitely indicates a bottleneck. If the CPU usage is high from non-pull-query workloads, it could still be impacting pull queries.

> I'm trying to evaluate the bottleneck during a Pull Query. Do you have any recommendations how to approach that?

Not besides the metrics that I already mentioned above, for trying to tease apart whether it's a server-side limitation or something else. On the server side, inspecting the usual server utilization metrics (CPU, disk I/O, etc) as you already seem to be doing sounds like the way to go.

> I tried calling the API again with 1000 keys in the WHERE clause and it returned within 40 seconds.

It could be worth experimenting to see whether it's faster to issue a single query with 1000 keys in the WHERE clause, or 1000 queries each with `WHERE <keyCol> = <value>` rather than `WHERE <keyCol> IN (<values>)`. Naively I wouldn't expect a difference but I vaguely recall reports of `WHERE <keyCol> IN (<values>)` slowing down if there are too many values, so it's worth experimenting with.

**Comment by Rap70r** [comment]
Hi @vcrfxia, I appreciate the detailed answer. We will definitely look into your suggestions and adjust accordingly. One last thing. Can you please confirm that we can utilize ksqlDB for our use case? Basically, we have analytical data sitting on SQL Server that ranges across multiple tables and each table ranges from 300K to 100 Million records. We are currently streaming the data into a Kafka cluster using a Kafka Connector. What we are trying to evaluate is if we can utilize ksqlDB's materialized views to apply aggregations and joins against Kafka Topic data and utilize ksqlDB's RESTful API to make pull query requests against millions of records based on custom filters.

Thank you

**Comment by vcrfxia** [comment]
It's definitely possible, assuming adequate parallelization (partitioning, and also additional server instances as needed) and resource provisioning. It sounds like the main question will be whether the performance meets your requirements. ksqlDB performance is not optimized for pull queries, as its architectural focus has been stream processing instead.

**Comment by Rap70r** [comment]
Thank you, @vcrfxia. we can definitely perform benchmark load tests and examine that case. Just a clarification, does pull query performance accept tuning? With customized configuration and proper server parallelization, is it possible to adjust its performance?

Thank you

**Comment by vcrfxia** [comment]
Yes, but only up to a point. ksqlDB pull queries (on that scale of data) will never be as performant as systems optimized for key-based lookups.

**Comment by Rap70r** [comment]
Understood. Thank you so much for your time. We will go over your suggestions and provided resources to make proper changes and perform load tests. I think we can close this issue.
